# Generated by Django 3.2.19 on 2023-06-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('latitud', models.FloatField(help_text='Introduïu la latitud (copiada de Google Maps)')),
                ('longitud', models.FloatField(help_text='Introduïu la longitud (copiada de Google Maps)')),
                ('icono', models.CharField(choices=[('station', 'Estació'), ('restaurant', 'Restaurant'), ('library', 'Biblioteca'), ('hotel', 'Hotel'), ('town-hall', 'Ajuntament'), ('theater', 'Centre Cultural')], max_length=100)),
            ],
            options={
                'verbose_name': 'Punt de mapa',
                'verbose_name_plural': 'Punts de mapa',
            },
        ),
    ]
