# Generated by Django 3.2.19 on 2023-06-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='icono',
            field=models.CharField(choices=[('station', 'Estació'), ('restaurant', 'Restaurant'), ('library', 'Biblioteca'), ('hotel', 'Hotel'), ('town-hall', 'Ajuntament'), ('theater', 'Centre Cultural'), ('sport', 'Esports'), ('serveis', 'Serveis'), ('transports', 'Transports'), ('aparcaments', 'Aparcaments')], max_length=100),
        ),
    ]
