# Generated by Django 3.2.19 on 2023-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_mappoint_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='publicado',
            field=models.BooleanField(default=False, help_text='publicat?'),
        ),
    ]
