# Generated by Django 4.2.2 on 2023-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_mappoint_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='icono',
            field=models.CharField(choices=[('station', 'Estació'), ('restaurant', 'Restaurant'), ('library', 'Biblioteca'), ('hotel', 'Hotel'), ('town-hall', 'Ajuntament'), ('theater', 'Centre Cultural'), ('sport', 'Esports'), ('serveis', 'Serveis'), ('transports', 'Transports'), ('aparcaments', 'Aparcaments'), ('platges', 'Platges'), ('informació', "Punt d'informació")], max_length=100),
        ),
    ]
