# Generated by Django 4.2.2 on 2023-06-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_alter_post_titulo'),
        ('map', '0007_alter_mappoint_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappoint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='publicado',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='titulo',
        ),
    ]
