# Generated by Django 4.2.2 on 2023-06-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_remove_mappoint_id_remove_mappoint_publicado_and_more'),
        ('map', '0009_auto_20230627_0941'),
    ]

    operations = [
    ]
