# Generated by Django 4.2.2 on 2023-06-27 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_alter_post_titulo'),
        ('map', '0010_merge_20230627_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post'),
            preserve_default=False,
        ),
    ]
