# Generated by Django 4.2.2 on 2023-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_mappoint_post_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='icono',
            field=models.CharField(choices=[('station', 'Estació'), ('restaurant', 'Restaurant'), ('library', 'Biblioteca'), ('hotel', 'Hotel'), ('town-hall', 'Ajuntament'), ('theater', 'Centre Cultural'), ('sport', 'Esports'), ('serveis', 'Serveis'), ('transports', 'Transports'), ('aparcaments', 'Aparcaments'), ('platges', 'Platges'), ('informació', "Punt d'informació"), ('jaciments', 'Jaciments arqueològics'), ('patrimoni', 'Patrimoni cultural'), ('flora-i-fauna', 'flora i fauna')], max_length=100),
        ),
    ]
