# Generated by Django 4.2.2 on 2023-07-06 11:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_alter_mappoint_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='contenido_adicional',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Texto adicional', null=True),
        ),
    ]
