# Generated by Django 4.2.2 on 2023-07-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_mappoint_contenido_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='calle',
            field=models.CharField(blank=True, help_text='Carrer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='codigo_postal',
            field=models.CharField(default='08349', editable=False, help_text='Codi postal', max_length=10),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='comarca',
            field=models.CharField(default='Maresme', editable=False, help_text='Comarca', max_length=100),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='comunidad_autonoma',
            field=models.CharField(default='Catalunya', editable=False, help_text='Comunitat Autònoma', max_length=100),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='municipio',
            field=models.CharField(default='Cabrera de Mar', editable=False, help_text='Municipi', max_length=100),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='pais',
            field=models.CharField(default='Espanya', editable=False, help_text='País', max_length=100),
        ),
    ]
