# Generated by Django 4.2.1 on 2023-05-15 06:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('privacitat', 'Política de privacitat'), ('avis_legal', 'Avís legal'), ('cookies', 'Política de cookies')], max_length=20, unique=True)),
                ('encabezado', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='legal_images/')),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
