# Generated by Django 4.2.1 on 2023-05-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginalegal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='legal_images/'),
        ),
    ]
