# Generated by Django 4.2.2 on 2024-04-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('ca', 'Catalán'), ('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés')], max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Traducció',
                'verbose_name_plural': 'Traduccions',
            },
        ),
    ]
