# Generated by Django 4.2.2 on 2024-04-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traducciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='language_code',
            field=models.CharField(choices=[('ca', 'Català'), ('es', 'Espanyol'), ('en', 'Anglès'), ('fr', 'Francès')], default='ca', max_length=2, unique=True),
        ),
    ]
