# Generated by Django 4.2 on 2023-05-25 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internallink',
            name='slide',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.slide'),
        ),
    ]
