# Generated by Django 4.2 on 2023-05-25 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0003_remove_slide_carrusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='carrusel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='personalizacion.carrusel'),
            preserve_default=False,
        ),
    ]
