# Generated by Django 4.2 on 2023-05-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0004_slide_carrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='carrusel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='personalizacion.carrusel'),
        ),
    ]
