# Generated by Django 4.2 on 2023-05-25 05:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0005_alter_slide_carrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='carrusel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='personalizacion.carrusel'),
            preserve_default=False,
        ),
    ]
