# Generated by Django 4.2 on 2023-05-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0007_alter_internallink_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='carrusel',
        ),
        migrations.AddField(
            model_name='carrusel',
            name='elementos',
            field=models.ManyToManyField(blank=True, related_name='carruseles', to='personalizacion.slide'),
        ),
    ]
