# Generated by Django 4.2 on 2023-05-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0008_remove_slide_carrusel_carrusel_elementos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrusel',
            name='elementos',
        ),
        migrations.AddField(
            model_name='carrusel',
            name='elemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carruseles', to='personalizacion.slide'),
        ),
    ]
