# Generated by Django 4.2 on 2023-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0010_remove_carrusel_elemento_carrusel_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='slides',
            field=models.ManyToManyField(null=True, related_name='carruseles', to='personalizacion.slide'),
        ),
    ]
