# Generated by Django 4.2 on 2023-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0011_alter_carrusel_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='slides',
            field=models.ManyToManyField(blank=True, related_name='carruseles', to='personalizacion.slide'),
        ),
    ]
