# Generated by Django 4.2 on 2023-05-26 06:24

from django.db import migrations, models
import personalizacion.utils


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0012_alter_carrusel_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parallax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion_corta', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to=personalizacion.utils.get_parallax_image_path)),
                ('publicado', models.BooleanField(default=False)),
            ],
        ),
    ]
