# Generated by Django 3.2.19 on 2023-06-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0007_video'),
        ('personalizacion', '0013_parallax'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortadaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideosPortada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portadavideo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.portadavideo')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.video')),
            ],
        ),
    ]
