# Generated by Django 3.2.19 on 2023-06-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0015_auto_20230605_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosportada',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
