# Generated by Django 3.2.19 on 2023-06-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_alter_categoria_slug'),
        ('personalizacion', '0017_portadavideo_publicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarruselSubBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrusel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizacion.carrusel')),
                ('subblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subblog')),
            ],
            options={
                'verbose_name': 'Carrusel de SubBlog',
                'verbose_name_plural': 'Carruseles de SubBlogs',
            },
        ),
    ]
