# Generated by Django 4.2.2 on 2023-06-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0019_selecciondestacados'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecciondestacados',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Marca si quieres que sea despublicado.'),
        ),
    ]
