# Generated by Django 4.2.2 on 2023-07-26 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0009_alter_video_archivo'),
        ('personalizacion', '0020_selecciondestacados_publicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosportada',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='videosportada',
            name='videos',
        ),
        migrations.AddField(
            model_name='videosportada',
            name='videos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.video'),
        ),
    ]
