# Generated by Django 4.2.2 on 2023-08-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0022_videosembed_remove_videosportada_portadavideo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarruselSubBlog',
        ),
    ]
