# Generated by Django 4.2.2 on 2023-08-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0024_alter_parallax_descripcion_corta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeleccionDestacados',
        ),
    ]
