# Generated by Django 4.2.2 on 2023-09-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0013_fichero_titulo'),
        ('topbar', '0011_alter_topbar_descripcion_and_more'),
        ('blog', '0079_alter_categoria_tipo'),
        ('personalizacion', '0025_delete_selecciondestacados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalizacion',
            options={'verbose_name': 'Personalització', 'verbose_name_plural': 'Personalitzacions'},
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='analytics_script',
            field=models.TextField(blank=True, help_text='Col·loca aquí el teu codi de Google Analytics.', null=True, verbose_name='Script de Google Analytics'),
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='meta_description_portada',
            field=models.TextField(blank=True, help_text='Especifica una descripció meta per a la portada del lloc.', null=True, verbose_name='Meta descripció de portada'),
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, help_text='Selecciona les paraules clau meta relacionades amb el lloc.', null=True, to='blog.tag', verbose_name='Paraules clau meta'),
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='parallax_portada',
            field=models.OneToOneField(blank=True, help_text="Selecciona el parallax per a la portada (si n'hi ha un).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.parallax', verbose_name='Parallax de portada'),
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='topbar',
            field=models.OneToOneField(blank=True, help_text='Selecciona el topbar que vols per la portada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='topbar.topbar', verbose_name='Topbar del portal'),
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='video_portada',
            field=models.OneToOneField(blank=True, help_text="Selecciona el vídeo per a la portada (si n'hi ha un).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='multimedia_manager.video', verbose_name='Vídeo de portada'),
        ),
        migrations.AlterField(
            model_name='personalizacion',
            name='favicon',
            field=models.OneToOneField(blank=True, help_text="Selecciona el favicon per al lloc (si n'hi ha un).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.favicon', verbose_name='Favicon'),
        ),
    ]
