# Generated by Django 4.2.2 on 2023-09-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0013_fichero_titulo'),
        ('blog', '0079_alter_categoria_tipo'),
        ('personalizacion', '0026_alter_personalizacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosembed',
            name='videos',
        ),
        migrations.AddField(
            model_name='videosembed',
            name='video',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='multimedia_manager.video'),
        ),
        migrations.AlterField(
            model_name='personalizacion',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, help_text='Selecciona les paraules clau meta relacionades amb el lloc.', to='blog.tag', verbose_name='Paraules clau meta'),
        ),
    ]
