# Generated by Django 4.2.2 on 2023-10-04 07:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import personalizacion.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0079_alter_categoria_tipo'),
        ('personalizacion', '0027_remove_videosembed_videos_videosembed_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrusel',
            options={'verbose_name': 'Carrusel', 'verbose_name_plural': 'Carrusels'},
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicat'),
        ),
        migrations.AlterField(
            model_name='favicon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Imatge'),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='entrada'),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='tipo',
            field=models.CharField(choices=[('post', 'Post'), ('categoria', 'Categoría'), ('subblog', 'SubBlog')], max_length=10, verbose_name='Tipus'),
        ),
        migrations.AlterField(
            model_name='parallax',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AlterField(
            model_name='parallax',
            name='imagen',
            field=models.ImageField(upload_to=personalizacion.utils.get_parallax_image_path, verbose_name='Imatge'),
        ),
        migrations.AlterField(
            model_name='parallax',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicat'),
        ),
        migrations.AlterField(
            model_name='parallax',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Text que apareix el centre de la imatge.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='imagen',
            field=models.ImageField(upload_to='slides/', verbose_name='Imatge'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='videosembed',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicat'),
        ),
        migrations.AlterField(
            model_name='videosembed',
            name='titulo',
            field=models.CharField(help_text='Títol del Vídeo.', max_length=100, verbose_name='Títol'),
        ),
        migrations.CreateModel(
            name='TrenPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(help_text="Títol de 'com arribar a Cabrera amb tren'.", max_length=100, verbose_name='Títol')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True)),
                ('enlace', models.URLField(blank=True, help_text='enllaç cap a els horaris del tren', verbose_name='enllaç')),
                ('personalizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.personalizacion', verbose_name='Personalització')),
            ],
            options={
                'verbose_name': 'Tren',
                'verbose_name_plural': 'Trens',
            },
        ),
        migrations.CreateModel(
            name='BusPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(help_text="Títol de 'com arribar a Cabrera de Mar amb bus'.", max_length=100, verbose_name='Títol')),
                ('descripcion', models.TextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', max_length=100, null=True)),
                ('enlace', models.URLField(blank=True, help_text='enllaç cap els horaris del bus.', verbose_name='enllaç')),
                ('personalizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.personalizacion', verbose_name='Personalització')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Busos',
            },
        ),
        migrations.CreateModel(
            name='AutoPistaPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(help_text="Títol de 'com arribar a Cabrera per autopista'.", max_length=100, verbose_name='Títol')),
                ('descripcion', models.TextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', max_length=100, null=True)),
                ('enlace', models.URLField(blank=True, help_text='enllaç cap a Cabrera de Mar.', verbose_name='enllaç')),
                ('personalizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.personalizacion', verbose_name='Personalització')),
            ],
            options={
                'verbose_name': 'Autopista',
                'verbose_name_plural': 'Autopistes',
            },
        ),
        migrations.CreateModel(
            name='AeropuertoPErsonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(help_text="Títol de 'com arribar a Cabrera de Mar amb avió'.", max_length=100, verbose_name='Títol')),
                ('descripcion', models.TextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', max_length=100, null=True)),
                ('enlace_principal', models.URLField(blank=True, help_text='enllaç cap els horaris del bus.', verbose_name='enllaç')),
                ('enlace_secundario', models.URLField(blank=True, help_text='enllaç cap els horaris del bus.', verbose_name='enllaç')),
                ('personalizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.personalizacion', verbose_name='Personalització')),
            ],
            options={
                'verbose_name': 'Aeroport',
                'verbose_name_plural': 'Aeroports',
            },
        ),
    ]
