# Generated by Django 4.2.2 on 2023-10-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0028_alter_carrusel_options_alter_carrusel_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='titulo',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera de Mar amb avió'.", max_length=100, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='autopistapersonalizacion',
            name='titulo',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera per autopista'.", max_length=100, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='buspersonalizacion',
            name='titulo',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera de Mar amb bus'.", max_length=100, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='trenpersonalizacion',
            name='titulo',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera amb tren'.", max_length=100, verbose_name='Títol'),
        ),
    ]
