# Generated by Django 4.2.2 on 2023-10-04 07:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0029_alter_aeropuertopersonalizacion_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autopistapersonalizacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buspersonalizacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', max_length=100, null=True),
        ),
    ]
