# Generated by Django 4.2.2 on 2023-10-04 07:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0030_alter_aeropuertopersonalizacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True),
        ),
        migrations.AlterField(
            model_name='autopistapersonalizacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True),
        ),
        migrations.AlterField(
            model_name='buspersonalizacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True),
        ),
    ]
