# Generated by Django 4.2.2 on 2023-10-04 08:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0031_alter_aeropuertopersonalizacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='enlace_principal',
            field=models.URLField(blank=True, help_text='enllaç cap els horaris del bus.', verbose_name='enllaç principal'),
        ),
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='enlace_secundario',
            field=models.URLField(blank=True, help_text='enllaç cap els horaris del bus.', verbose_name='enllaç secundari'),
        ),
        migrations.AlterField(
            model_name='autopistapersonalizacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='buspersonalizacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='trenpersonalizacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True, verbose_name='Descripció'),
        ),
    ]
