# Generated by Django 4.2.2 on 2023-10-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0032_alter_aeropuertopersonalizacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='personalizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.personalizacion', verbose_name='Personalització'),
        ),
        migrations.AlterField(
            model_name='autopistapersonalizacion',
            name='personalizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.personalizacion', verbose_name='Personalització'),
        ),
        migrations.AlterField(
            model_name='buspersonalizacion',
            name='personalizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.personalizacion', verbose_name='Personalització'),
        ),
        migrations.AlterField(
            model_name='trenpersonalizacion',
            name='personalizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.personalizacion', verbose_name='Personalització'),
        ),
    ]
