# Generated by Django 4.2.2 on 2023-10-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0033_alter_aeropuertopersonalizacion_personalizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaParallax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Títol del parallax.', max_length=100, verbose_name='Títol')),
                ('parallax_agenda', models.OneToOneField(help_text="Selecciona el parallax per a l'agenda (si n'hi ha un).", on_delete=django.db.models.deletion.CASCADE, to='personalizacion.parallax', verbose_name="Parallax de l'agenda")),
            ],
            options={
                'verbose_name': "Imatge per l'agenda",
                'verbose_name_plural': "Imatges per l'agenda",
            },
        ),
    ]
