# Generated by Django 4.2.2 on 2023-10-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0035_personalizacion_parallax_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizacion',
            name='parallax_agenda',
        ),
    ]
