# Generated by Django 4.2.2 on 2023-10-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0036_remove_personalizacion_parallax_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='parallax_agenda',
            field=models.OneToOneField(blank=True, help_text="Selecciona el parallax per l'agenda (si n'hi ha un).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.agendaparallax', verbose_name="Parallax de l'agenda"),
        ),
    ]
