# Generated by Django 4.2.2 on 2023-11-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0015_parallax_videosembed'),
        ('eventos_especiales', '0019_alter_eventoespecial_parallax'),
        ('personalizacion', '0038_remove_internallink_slide_delete_carrusel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosembed',
            name='video',
        ),
        migrations.AlterField(
            model_name='agendaparallax',
            name='parallax_agenda',
            field=models.OneToOneField(help_text="Selecciona el parallax per a l'agenda (si n'hi ha un).", on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.parallax', verbose_name="Parallax de l'agenda"),
        ),
        migrations.AlterField(
            model_name='personalizacion',
            name='parallax_portada',
            field=models.OneToOneField(blank=True, help_text="Selecciona el parallax per a la portada (si n'hi ha un).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='multimedia_manager.parallax', verbose_name='Parallax de portada'),
        ),
        migrations.DeleteModel(
            name='Parallax',
        ),
        migrations.DeleteModel(
            name='VideosEmbed',
        ),
    ]
