# Generated by Django 4.2.2 on 2023-11-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0039_remove_videosembed_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizacion',
            name='parallax_agenda',
        ),
        migrations.DeleteModel(
            name='AgendaParallax',
        ),
    ]
