# Generated by Django 4.2.2 on 2023-11-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0016_alter_parallax_titulo_alter_videosembed_titulo'),
        ('personalizacion', '0040_remove_personalizacion_parallax_agenda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaParallax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Títol del parallax.', max_length=100, verbose_name='Títol')),
                ('parallax_agenda', models.OneToOneField(help_text="Selecciona el parallax per a l'agenda (si n'hi ha un).", on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.parallax', verbose_name="Parallax de l'agenda")),
            ],
            options={
                'verbose_name': "Imatge per l'agenda",
                'verbose_name_plural': "Imatges per l'agenda",
            },
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='parallax_agenda',
            field=models.OneToOneField(blank=True, help_text="Selecciona el parallax per l'agenda (si n'hi ha un).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.agendaparallax', verbose_name="Parallax de l'agenda"),
        ),
    ]
