# Generated by Django 4.2.2 on 2023-11-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0019_alter_eventoespecial_parallax'),
        ('compra_y_descubre', '0015_alter_compradescubre_qr_code'),
        ('personalizacion', '0041_agendaparallax_personalizacion_parallax_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='internallink',
            name='compra_y_descubre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra_y_descubre.compradescubre', verbose_name='Compra i descobreix'),
        ),
        migrations.AddField(
            model_name='internallink',
            name='evento_especial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos_especiales.eventoespecial', verbose_name='Esdeveniment especial'),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='tipo',
            field=models.CharField(choices=[('post', 'Post'), ('categoria', 'Categoría'), ('subblog', 'SubBlog'), ('eventos_especiales', 'Esdeveniments especials'), ('compra_y_descubre', 'Compra i descobreix')], max_length=20, verbose_name='Tipus'),
        ),
        migrations.CreateModel(
            name='SuperDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Títol del super destacat.', max_length=100, verbose_name='Títol')),
                ('destacado', models.OneToOneField(help_text='Selecciona un enllaç intern per fer la vinculació', on_delete=django.db.models.deletion.CASCADE, to='personalizacion.internallink', verbose_name='Destacat')),
            ],
            options={
                'verbose_name': 'Imatge pel super destacat',
                'verbose_name_plural': 'Imatges pels super destacats',
            },
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='super_destacado',
            field=models.OneToOneField(blank=True, help_text='Selecciona un superdestacat si existeix.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.superdestacado', verbose_name='super destacat'),
        ),
    ]
