# Generated by Django 4.2.2 on 2023-11-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0042_internallink_compra_y_descubre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superdestacado',
            options={'verbose_name': 'Super destacat', 'verbose_name_plural': 'Super destacats'},
        ),
    ]
