# Generated by Django 4.2.2 on 2023-11-16 09:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0044_remove_internallink_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superdestacado',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Títol que sortirà com a encapçalament al superdestacat.', null=True, verbose_name='Descripció'),
        ),
    ]
