# Generated by Django 4.2.2 on 2023-11-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0045_superdestacado_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superdestacado',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Títol que sortirà com a encapçalament al superdestacat.', null=True, verbose_name='Descripció'),
        ),
    ]
