# Generated by Django 4.2.2 on 2023-11-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0046_alter_superdestacado_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='horario',
            field=models.CharField(choices=[('estiu', 'estiu'), ('hivern', 'hivern')], default='estiu', help_text="Selecciona el teu horari, serveix principalment per donar suport els components de la web amb el canvi d'horari quan fa falta.", max_length=20, verbose_name='Horari'),
        ),
    ]
