# Generated by Django 4.2.2 on 2023-11-22 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0047_personalizacion_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='hora_agenda_fin',
            field=models.TimeField(default=datetime.time(2, 0), help_text="Durada dels esdeveniments de l'agenda.", verbose_name='temps per defecte dels esdeveniments'),
        ),
    ]
