# Generated by Django 4.2.2 on 2023-12-01 09:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0048_personalizacion_hora_agenda_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Títol de la mesura')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripció')),
                ('impacto_economico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Impacte Econòmic Estimat')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicat')),
            ],
            options={
                'verbose_name': 'Mesura Econòmica',
                'verbose_name_plural': 'Mesura Econòmiques',
            },
        ),
    ]
