# Generated by Django 4.2.2 on 2023-12-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0049_medidaeconomica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedidaEconomica',
        ),
    ]
