# Generated by Django 4.2.2 on 2024-02-19 12:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0050_delete_medidaeconomica'),
    ]

    operations = [
        migrations.AddField(
            model_name='trenpersonalizacion',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='trenpersonalizacion',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='trenpersonalizacion',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='trenpersonalizacion',
            name='titulo_ca',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera amb tren'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='trenpersonalizacion',
            name='titulo_en',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera amb tren'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='trenpersonalizacion',
            name='titulo_es',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera amb tren'.", max_length=100, null=True, verbose_name='Títol'),
        ),
    ]
