# Generated by Django 4.2.2 on 2024-02-19 13:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0051_trenpersonalizacion_descripcion_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuertopersonalizacion',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='aeropuertopersonalizacion',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='aeropuertopersonalizacion',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='aeropuertopersonalizacion',
            name='titulo_ca',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera de Mar amb avió'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='aeropuertopersonalizacion',
            name='titulo_en',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera de Mar amb avió'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='aeropuertopersonalizacion',
            name='titulo_es',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera de Mar amb avió'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='autopistapersonalizacion',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='autopistapersonalizacion',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='autopistapersonalizacion',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='autopistapersonalizacion',
            name='titulo_ca',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera per autopista'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='autopistapersonalizacion',
            name='titulo_en',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera per autopista'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='autopistapersonalizacion',
            name='titulo_es',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera per autopista'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='buspersonalizacion',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='buspersonalizacion',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='buspersonalizacion',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='buspersonalizacion',
            name='titulo_ca',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera de Mar amb bus'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='buspersonalizacion',
            name='titulo_en',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera de Mar amb bus'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='buspersonalizacion',
            name='titulo_es',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera de Mar amb bus'.", max_length=100, null=True, verbose_name='Títol'),
        ),
    ]
