# Generated by Django 4.2.2 on 2024-02-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0022_imagencarrusel_descripcion_and_more'),
        ('personalizacion', '0052_aeropuertopersonalizacion_descripcion_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='carrusel_portada',
            field=models.ForeignKey(blank=True, help_text="Selecciona el carrusel per a la portada (si n'hi ha un).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='multimedia_manager.carrusel', verbose_name='Carrusel de portada'),
        ),
    ]
