# Generated by Django 4.2.2 on 2024-02-27 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0053_personalizacion_carrusel_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='dias_vista_agenda',
            field=models.IntegerField(default=10, help_text="Defineix el nombre de dies a mostrar en la vista de l'agenda, des de 0 fins a 30.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name="Dies de vista de l'agenda"),
        ),
    ]
