# Generated by Django 4.2.2 on 2024-02-27 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0054_personalizacion_dias_vista_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizacion',
            name='dias_vista_agenda',
            field=models.IntegerField(default=10, help_text="Defineix el nombre de dies per generar el PDF de l'agenda, des de 0 fins a 30.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name="Dies pel PDF de l'agenda."),
        ),
    ]
