# Generated by Django 4.2.2 on 2024-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0055_alter_personalizacion_dias_vista_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='enlace_agenda',
            field=models.URLField(blank=True, help_text="Enllaç per comprar tiquets per l'agenda", null=True, verbose_name='enllaç pels tiquets'),
        ),
    ]
