# Generated by Django 4.2.2 on 2024-02-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0025_carrusel_tipo'),
        ('personalizacion', '0056_personalizacion_enlace_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='carrusel_agenda',
            field=models.ForeignKey(blank=True, help_text="Selecciona el carrusel-collage per a la portada (si n'hi ha un).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalizaciones_agenda', to='multimedia_manager.carrusel', verbose_name='Carrusel-collage de portada'),
        ),
        migrations.AlterField(
            model_name='personalizacion',
            name='carrusel_portada',
            field=models.ForeignKey(blank=True, help_text="Selecciona el carrusel per a la portada (si n'hi ha un).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalizaciones_portada', to='multimedia_manager.carrusel', verbose_name='Carrusel de portada'),
        ),
    ]
