# Generated by Django 4.2.2 on 2024-03-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0057_personalizacion_carrusel_agenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superdestacado',
            name='mostrar_descripcion',
            field=models.BooleanField(default=True, verbose_name='Mostrar descripció'),
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='mostrar_imagen',
            field=models.BooleanField(default=True, verbose_name='Mostrar imatge'),
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='mostrar_titulo',
            field=models.BooleanField(default=True, verbose_name='Mostrar títol'),
        ),
    ]
