# Generated by Django 4.2.2 on 2024-03-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0058_superdestacado_mostrar_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superdestacado',
            name='mostrar_imagen',
        ),
    ]
