# Generated by Django 4.2.2 on 2024-03-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0059_remove_superdestacado_mostrar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='superdestacado',
            name='descripcion_ca',
            field=models.TextField(blank=True, help_text='Títol que sortirà com a encapçalament al superdestacat.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Títol que sortirà com a encapçalament al superdestacat.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='descripcion_es',
            field=models.TextField(blank=True, help_text='Títol que sortirà com a encapçalament al superdestacat.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='titulo_ca',
            field=models.CharField(help_text='Títol del super destacat.', max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='titulo_en',
            field=models.CharField(help_text='Títol del super destacat.', max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='titulo_es',
            field=models.CharField(help_text='Títol del super destacat.', max_length=100, null=True, verbose_name='Títol'),
        ),
    ]
