# Generated by Django 4.2.2 on 2024-03-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0060_superdestacado_descripcion_ca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superdestacado',
            options={'ordering': ['orden'], 'verbose_name': 'Super destacat', 'verbose_name_plural': 'Super destacats'},
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text="Defineix l'ordre del destacat", verbose_name='Ordre'),
        ),
        migrations.RemoveField(
            model_name='personalizacion',
            name='super_destacado',
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='super_destacado',
            field=models.ManyToManyField(help_text='Selecciona un superdestacat si existeix.', to='personalizacion.superdestacado', verbose_name='super destacat'),
        ),
    ]
