# Generated by Django 4.2.2 on 2024-03-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0061_alter_superdestacado_options_superdestacado_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizacion',
            name='super_destacado',
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='personalizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.personalizacion', verbose_name='Personalització'),
        ),
    ]
