# Generated by Django 4.2.2 on 2024-03-21 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0062_remove_personalizacion_super_destacado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superdestacado',
            name='personalizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizacion.personalizacion', verbose_name='Personalització'),
        ),
    ]
