# Generated by Django 4.2.2 on 2024-04-06 20:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0063_alter_superdestacado_personalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuertopersonalizacion',
            name='descripcion_fr',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='aeropuertopersonalizacion',
            name='titulo_fr',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera de Mar amb avió'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='autopistapersonalizacion',
            name='descripcion_fr',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='autopistapersonalizacion',
            name='titulo_fr',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera per autopista'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='buspersonalizacion',
            name='descripcion_fr',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='buspersonalizacion',
            name='titulo_fr',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera de Mar amb bus'.", max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='descripcion_fr',
            field=models.TextField(blank=True, help_text='Títol que sortirà com a encapçalament al superdestacat.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='superdestacado',
            name='titulo_fr',
            field=models.CharField(help_text='Títol del super destacat.', max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='trenpersonalizacion',
            name='descripcion_fr',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='trenpersonalizacion',
            name='titulo_fr',
            field=models.CharField(help_text="Títol de 'com arribar a Cabrera amb tren'.", max_length=100, null=True, verbose_name='Títol'),
        ),
    ]
