# Generated by Django 4.2.2 on 2024-04-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0067_remove_personalizacion_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='video_url',
            field=models.URLField(blank=True, help_text="Afegeix aquí l'URL de l'iframe del vídeo de YouTube o d'una altra plataforma. Utilitza preferentment enllaços de 'youtube-nocookie' per millorar la privacitat.", null=True, verbose_name='URL del vídeo'),
        ),
    ]
