# Generated by Django 4.2.2 on 2024-04-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0068_personalizacion_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizacion',
            name='video_url',
        ),
    ]
