# Generated by Django 4.2.2 on 2024-04-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0069_remove_personalizacion_video_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IframeVideoHome',
        ),
    ]
