# Generated by Django 4.2.2 on 2024-04-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0071_iframevideohome_personalizacion_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='iframevideohome',
            name='description_ca',
            field=models.TextField(help_text='Descripció detallada del contingut del vídeo.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='iframevideohome',
            name='description_en',
            field=models.TextField(help_text='Descripció detallada del contingut del vídeo.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='iframevideohome',
            name='description_es',
            field=models.TextField(help_text='Descripció detallada del contingut del vídeo.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='iframevideohome',
            name='description_fr',
            field=models.TextField(help_text='Descripció detallada del contingut del vídeo.', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='iframevideohome',
            name='title_ca',
            field=models.CharField(help_text='Títol del vídeo que es mostrarà públicament.', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='iframevideohome',
            name='title_en',
            field=models.CharField(help_text='Títol del vídeo que es mostrarà públicament.', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='iframevideohome',
            name='title_es',
            field=models.CharField(help_text='Títol del vídeo que es mostrarà públicament.', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='iframevideohome',
            name='title_fr',
            field=models.CharField(help_text='Títol del vídeo que es mostrarà públicament.', max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
