# Generated by Django 4.2.2 on 2024-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0072_iframevideohome_description_ca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iframevideohome',
            name='description',
            field=models.TextField(blank=True, help_text='Descripció detallada del contingut del vídeo.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='iframevideohome',
            name='description_ca',
            field=models.TextField(blank=True, help_text='Descripció detallada del contingut del vídeo.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='iframevideohome',
            name='description_en',
            field=models.TextField(blank=True, help_text='Descripció detallada del contingut del vídeo.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='iframevideohome',
            name='description_es',
            field=models.TextField(blank=True, help_text='Descripció detallada del contingut del vídeo.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='iframevideohome',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Descripció detallada del contingut del vídeo.', null=True, verbose_name='Descripció'),
        ),
    ]
