# Generated by Django 4.2.2 on 2024-04-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0389_turismesostenible_color_impar_and_more'),
        ('personalizacion', '0073_alter_iframevideohome_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='alerta',
            field=models.OneToOneField(blank=True, help_text='Selecciona una Alerta per la portada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.agenda', verbose_name='Alerta'),
        ),
    ]
