# Generated by Django 4.2.2 on 2024-04-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0009_alerta_descripcion_fr_alerta_titulo_fr'),
        ('personalizacion', '0074_personalizacion_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizacion',
            name='alerta',
            field=models.OneToOneField(blank=True, help_text='Selecciona una Alerta per la portada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerta.alerta', verbose_name='Alerta'),
        ),
    ]
