# Generated by Django 4.2.2 on 2024-04-18 10:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0076_superdestacado_flyer_superdestacado_link_generico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superdestacado',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='superdestacado',
            name='link_generico',
            field=models.URLField(blank=True, help_text='Enllaç oblogatori quan no tenim viculat un descatat viculat.', null=True, verbose_name='Enlla genèric'),
        ),
    ]
