# Generated by Django 4.2.2 on 2024-04-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0027_imagencarrusel_descripcion_fr_and_more'),
        ('personalizacion', '0077_superdestacado_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizacion',
            name='carrusel_agenda',
            field=models.ForeignKey(blank=True, help_text="Selecciona el carrusel-collage per a la agenda (si n'hi ha un).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalizaciones_agenda', to='multimedia_manager.carrusel', verbose_name='Carrusel-collage de portada'),
        ),
    ]
