# Generated by Django 5.1.2 on 2025-10-08 19:49

import colorfield.fields
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0078_alter_personalizacion_carrusel_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='descripcion_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='descripcion_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='descripcion_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='aeropuertopersonalizacion',
            name='descripcion_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb avió.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='autopistapersonalizacion',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='autopistapersonalizacion',
            name='descripcion_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='autopistapersonalizacion',
            name='descripcion_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='autopistapersonalizacion',
            name='descripcion_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='autopistapersonalizacion',
            name='descripcion_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar per autopista.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='buspersonalizacion',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='buspersonalizacion',
            name='descripcion_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='buspersonalizacion',
            name='descripcion_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='buspersonalizacion',
            name='descripcion_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='buspersonalizacion',
            name='descripcion_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explicació de com arribar a Cabrera de Mar amb bus.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='superdestacado',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='trenpersonalizacion',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='trenpersonalizacion',
            name='descripcion_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='trenpersonalizacion',
            name='descripcion_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='trenpersonalizacion',
            name='descripcion_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='trenpersonalizacion',
            name='descripcion_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripció de com arribar a Cabrera de Mar amb tren.', null=True, verbose_name='Descripció'),
        ),
    ]
