# Generated by Django 4.2.2 on 2023-07-07 07:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalizacion', '0020_selecciondestacados_publicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0028_alter_visitaguiada_fecha_fin'),
        ('multimedia_manager', '0008_alter_video_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True)),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True)),
                ('titulo', models.CharField(help_text="Títol de l'esdeveniment especial", max_length=255)),
                ('slug', models.SlugField(editable=False, help_text='Slug automàtic generat a partir del títol', unique=True)),
                ('fecha_evento', models.DateField(default=django.utils.timezone.now, help_text="Data de l'esdeveniment")),
                ('descripcion_larga', ckeditor.fields.RichTextField(blank=True, help_text="Descripció llarga de l'esdeveniment especial", null=True)),
                ('descripcion_corta', models.TextField(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True)),
                ('logo_especial', models.ImageField(help_text="Logotip especial per a l'esdeveniment", upload_to='eventos_especiales/')),
                ('agendas', models.ManyToManyField(blank=True, help_text="Selecciona tots els esdeveniments vinculats amb l'event", related_name='agenda', to='agenda.agenda')),
                ('carruseles', models.ManyToManyField(blank=True, help_text="Carrussells relacionats amb l'esdeveniment especial (opcional)", to='personalizacion.carrusel')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('imagenes', models.ManyToManyField(blank=True, help_text="Imatges de l'esdeveniment especial (mínim 4)", related_name='eventos_especiales', to='multimedia_manager.imagen')),
                ('modificado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parallax', models.ForeignKey(blank=True, help_text="Parallax relacionat amb l'esdeveniment especial (opcional)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.parallax')),
                ('videos', models.ManyToManyField(blank=True, help_text="Videos relacionats amb l'esdeveniment especial (opcional)", to='multimedia_manager.video')),
            ],
            options={
                'verbose_name_plural': 'Esdeveniments Especials',
            },
        ),
        migrations.CreateModel(
            name='EventoFichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos_especiales.eventoespecial')),
                ('fichero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero')),
            ],
        ),
    ]
