# Generated by Django 4.2.2 on 2023-07-07 09:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0002_eventoespecial_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_corta',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True),
        ),
    ]
