# Generated by Django 4.2.2 on 2023-08-07 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0005_alter_eventoespecial_logo_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now, help_text="Data de finalització de l'esdeveniment"),
        ),
    ]
