# Generated by Django 4.2.2 on 2023-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0008_remove_eventoespecial_imagenes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='imagen_especial',
            field=models.ImageField(blank=True, help_text='miniatura que serveix per les seleccions i per les metadades', null=True, upload_to='eventos_especiales/'),
        ),
    ]
