# Generated by Django 4.2.2 on 2023-09-12 10:09

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0127_alter_visitaguiada_fecha_fin'),
        ('multimedia_manager', '0013_fichero_titulo'),
        ('personalizacion', '0025_delete_selecciondestacados'),
        ('eventos_especiales', '0010_alter_eventoespecial_metadescripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoespecial',
            name='agendas',
            field=models.ManyToManyField(blank=True, help_text="Selecciona tots els esdeveniments vinculats amb l'event", related_name='agenda', to='agenda.agenda', verbose_name='Agendes'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='carruseles',
            field=models.ManyToManyField(blank=True, help_text="Carrussells relacionats amb l'esdeveniment especial (opcional)", to='personalizacion.carrusel', verbose_name='Carrussells'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_corta',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_larga',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció llarga de l'esdeveniment especial", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='fecha_evento',
            field=models.DateField(default=django.utils.timezone.now, help_text="Data de l'esdeveniment", verbose_name="Data de l'esdeveniment"),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now, help_text="Data de finalització de l'esdeveniment", verbose_name='Data de finalització'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='imagen_especial',
            field=models.ImageField(blank=True, help_text='miniatura que serveix per les seleccions i per les metadades', null=True, upload_to='eventos_especiales/', verbose_name="Miniatura d'esdeveniment especial"),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='logo_especial',
            field=models.ImageField(blank=True, help_text="Logotip especial per a l'esdeveniment", null=True, upload_to='eventos_especiales/', verbose_name='Logotip especial'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='parallax',
            field=models.ForeignKey(blank=True, help_text="Parallax relacionat amb l'esdeveniment especial (opcional)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.parallax', verbose_name='Parallax'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='publicado',
            field=models.BooleanField(default=False, help_text="Indica si l'esdeveniment especial està publicat", verbose_name='Publicat'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='titulo',
            field=models.CharField(help_text="Títol de l'esdeveniment especial", max_length=255, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='videos',
            field=models.ManyToManyField(blank=True, help_text="Videos relacionats amb l'esdeveniment especial (opcional)", to='multimedia_manager.video', verbose_name='Vídeos'),
        ),
    ]
