# Generated by Django 4.2.2 on 2023-09-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_categoria_tags'),
        ('eventos_especiales', '0011_alter_eventoespecial_agendas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tags'),
        ),
    ]
