# Generated by Django 4.2.2 on 2023-09-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_categoria_tags'),
        ('eventos_especiales', '0012_eventoespecial_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Selecciona la categoria vinculada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='blog.categoria', verbose_name='Categoria'),
        ),
    ]
