# Generated by Django 4.2.2 on 2023-11-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0014_alter_eventoespecial_agendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
