# Generated by Django 4.2.2 on 2023-11-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0015_parallax_videosembed'),
        ('eventos_especiales', '0018_remove_eventoespecial_carruseles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoespecial',
            name='parallax',
            field=models.ForeignKey(blank=True, help_text="Parallax relacionat amb l'esdeveniment especial (opcional)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='multimedia_manager.parallax', verbose_name='Parallax'),
        ),
    ]
