# Generated by Django 4.2.2 on 2023-11-30 14:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0019_alter_eventoespecial_parallax'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='costo_antes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Cost de'abans", max_digits=10, verbose_name='Cost antic'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='costo_despues',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost actual', max_digits=10, verbose_name='Cost actual'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='mostrar_ahorro',
            field=models.BooleanField(default=False, help_text='Marca si vols que es mostri els preus', verbose_name="Mostrar l'estalvi"),
        ),
    ]
