# Generated by Django 4.2.2 on 2023-12-01 11:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0020_eventoespecial_costo_antes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Afegeix el títol de la mesura.', max_length=200, verbose_name='Títol de la mesura')),
                ('descripcion', ckeditor.fields.RichTextField(help_text='Afegeix la descripció de la mesura econòmica.', verbose_name='Descripció')),
                ('impacto_economico', models.DecimalField(decimal_places=2, help_text="Afegeix l'augment o l'estalvi de €.", max_digits=10, verbose_name='Impacte Econòmic Estimat')),
                ('publicado', models.BooleanField(default=False, help_text='Marca si la mesura està disponible.', verbose_name='Publicat')),
            ],
            options={
                'verbose_name': 'Mesures Econòmica',
                'verbose_name_plural': 'Mesures Econòmiques',
            },
        ),
    ]
