# Generated by Django 4.2.2 on 2023-12-01 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0021_medidaeconomica'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='medida_economica',
            field=models.ForeignKey(blank=True, help_text="Mesura o pla econòmic per l'esdeveniment especial (opcional)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos_especiales.medidaeconomica', verbose_name='Mesura econòmica'),
        ),
    ]
