# Generated by Django 4.2.2 on 2023-12-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0022_eventoespecial_medida_economica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoespecial',
            name='costo_antes',
        ),
        migrations.RemoveField(
            model_name='eventoespecial',
            name='costo_despues',
        ),
        migrations.AddField(
            model_name='medidaeconomica',
            name='titulo_html',
            field=models.CharField(default='texto de ejemplo', help_text='Afegeix el títol de la mesura per la web.', max_length=200, verbose_name='Títol de la mesura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medidaeconomica',
            name='titulo',
            field=models.CharField(help_text='Afegeix el nom de la mesura .', max_length=200, verbose_name='Nom de la mesura'),
        ),
    ]
