# Generated by Django 4.2.2 on 2023-12-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0023_remove_eventoespecial_costo_antes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidaeconomica',
            name='descripcion',
            field=models.TextField(help_text='Afegeix la descripció de la mesura econòmica per la web(sortirà el popup).', verbose_name='Descripció'),
        ),
    ]
