# Generated by Django 4.2.2 on 2023-12-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0024_alter_medidaeconomica_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Afegix el nom i cognom.', max_length=100, verbose_name='Nom')),
                ('cargo', models.CharField(max_length=100, verbose_name='càrrec')),
                ('foto', models.ImageField(blank=True, height_field="Afegeix un foto per l'autor", null=True, upload_to='autores/', verbose_name='Imatge')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text="Afegeix un missatge per l'esdeveniment", verbose_name='comentari')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(help_text='Afegeix un Autor del comentari', on_delete=django.db.models.deletion.CASCADE, to='eventos_especiales.autor', verbose_name='Autor')),
            ],
        ),
    ]
