# Generated by Django 4.2.2 on 2023-12-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0025_autor_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_especial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos_especiales.eventoespecial', verbose_name='esdeveniment especial')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos_especiales.mensaje', verbose_name='missatge')),
            ],
            options={
                'unique_together': {('evento_especial', 'mensaje')},
            },
        ),
    ]
