# Generated by Django 4.2.2 on 2023-12-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0026_eventomensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='fecha_publicacion',
        ),
    ]
