# Generated by Django 4.2.2 on 2023-12-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0027_remove_mensaje_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, help_text="Afegeix un foto per l'autor", null=True, upload_to='autores/', verbose_name='Imatge'),
        ),
    ]
