# Generated by Django 4.2.2 on 2023-12-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0029_alter_mensaje_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='mensaje_despedida',
            field=models.CharField(blank=True, help_text="Afegeix un missatge de comiat, per exemple: 'Bon Nadal' o 'Bon Nadal i feliç 2023!'", max_length=255, null=True, verbose_name='Missatge de comiat'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='titulo',
            field=models.CharField(default='cambiame', help_text="Afegeix el títol del missatge, per exemple: 'Dies de família, dies de poble' o 'Les entitats, pilar fonamental de Nadal'", max_length=255, verbose_name='Títol'),
            preserve_default=False,
        ),
    ]
