# Generated by Django 4.2.2 on 2023-12-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0030_mensaje_mensaje_despedida_mensaje_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='nombre_interno',
            field=models.CharField(default='cambiame', help_text="Afegeix un nom intern per al missatge, per exemple: 'Missatge del Nadal 2023 de Sergi Teodoro'", max_length=255, verbose_name='Nom intern'),
            preserve_default=False,
        ),
    ]
