# Generated by Django 4.2.2 on 2023-12-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0031_mensaje_nombre_interno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'verbose_name': 'missatge', 'verbose_name_plural': "Missatges de l'esdeveniment"},
        ),
    ]
