# Generated by Django 4.2.2 on 2024-02-19 09:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0032_alter_mensaje_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='descripcion_corta_ca',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='descripcion_corta_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='descripcion_corta_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='descripcion_larga_ca',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció llarga de l'esdeveniment especial", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='descripcion_larga_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció llarga de l'esdeveniment especial", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='descripcion_larga_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció llarga de l'esdeveniment especial", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='titulo_ca',
            field=models.CharField(help_text="Títol de l'esdeveniment especial", max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='titulo_en',
            field=models.CharField(help_text="Títol de l'esdeveniment especial", max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='titulo_es',
            field=models.CharField(help_text="Títol de l'esdeveniment especial", max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
