# Generated by Django 4.2.2 on 2024-02-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0033_eventoespecial_descripcion_corta_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidaeconomica',
            name='descripcion_ca',
            field=models.TextField(help_text='Afegeix la descripció de la mesura econòmica per la web(sortirà el popup).', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='medidaeconomica',
            name='descripcion_en',
            field=models.TextField(help_text='Afegeix la descripció de la mesura econòmica per la web(sortirà el popup).', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='medidaeconomica',
            name='descripcion_es',
            field=models.TextField(help_text='Afegeix la descripció de la mesura econòmica per la web(sortirà el popup).', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='medidaeconomica',
            name='titulo_html_ca',
            field=models.CharField(help_text='Afegeix el títol de la mesura per la web.', max_length=200, null=True, verbose_name='Títol de la mesura'),
        ),
        migrations.AddField(
            model_name='medidaeconomica',
            name='titulo_html_en',
            field=models.CharField(help_text='Afegeix el títol de la mesura per la web.', max_length=200, null=True, verbose_name='Títol de la mesura'),
        ),
        migrations.AddField(
            model_name='medidaeconomica',
            name='titulo_html_es',
            field=models.CharField(help_text='Afegeix el títol de la mesura per la web.', max_length=200, null=True, verbose_name='Títol de la mesura'),
        ),
    ]
