# Generated by Django 4.2.2 on 2024-02-19 12:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0034_medidaeconomica_descripcion_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='contenido_ca',
            field=ckeditor.fields.RichTextField(help_text="Afegeix un missatge per l'esdeveniment", null=True, verbose_name='comentari'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='contenido_en',
            field=ckeditor.fields.RichTextField(help_text="Afegeix un missatge per l'esdeveniment", null=True, verbose_name='comentari'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='contenido_es',
            field=ckeditor.fields.RichTextField(help_text="Afegeix un missatge per l'esdeveniment", null=True, verbose_name='comentari'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='mensaje_despedida_ca',
            field=models.CharField(blank=True, help_text="Afegeix un missatge de comiat, per exemple: 'Bon Nadal' o 'Bon Nadal i feliç 2023!'", max_length=255, null=True, verbose_name='Missatge de comiat'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='mensaje_despedida_en',
            field=models.CharField(blank=True, help_text="Afegeix un missatge de comiat, per exemple: 'Bon Nadal' o 'Bon Nadal i feliç 2023!'", max_length=255, null=True, verbose_name='Missatge de comiat'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='mensaje_despedida_es',
            field=models.CharField(blank=True, help_text="Afegeix un missatge de comiat, per exemple: 'Bon Nadal' o 'Bon Nadal i feliç 2023!'", max_length=255, null=True, verbose_name='Missatge de comiat'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='titulo_ca',
            field=models.CharField(help_text="Afegeix el títol del missatge, per exemple: 'Dies de família, dies de poble' o 'Les entitats, pilar fonamental de Nadal'", max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='titulo_en',
            field=models.CharField(help_text="Afegeix el títol del missatge, per exemple: 'Dies de família, dies de poble' o 'Les entitats, pilar fonamental de Nadal'", max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='titulo_es',
            field=models.CharField(help_text="Afegeix el títol del missatge, per exemple: 'Dies de família, dies de poble' o 'Les entitats, pilar fonamental de Nadal'", max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
