# Generated by Django 4.2.2 on 2024-02-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0035_mensaje_contenido_ca_mensaje_contenido_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='cargo_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='càrrec'),
        ),
        migrations.AddField(
            model_name='autor',
            name='cargo_en',
            field=models.CharField(max_length=100, null=True, verbose_name='càrrec'),
        ),
        migrations.AddField(
            model_name='autor',
            name='cargo_es',
            field=models.CharField(max_length=100, null=True, verbose_name='càrrec'),
        ),
    ]
