# Generated by Django 4.2.2 on 2024-02-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0036_autor_cargo_ca_autor_cargo_en_autor_cargo_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='flyer',
            field=models.ImageField(blank=True, help_text="Puja el flyer de l'esdeveniment en format DIN A3", null=True, upload_to='eventos_especiales/flyers/', verbose_name='Flyer'),
        ),
    ]
