# Generated by Django 4.2.2 on 2024-03-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0037_eventoespecial_flyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoespecial',
            options={'ordering': ['-fecha_evento'], 'verbose_name_plural': 'Esdeveniments Especials'},
        ),
    ]
