# Generated by Django 4.2.2 on 2024-04-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0040_eventoespecial_link_google_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='boton_texto_google_form',
            field=models.CharField(blank=True, help_text="Títol pel botó de l'enllaç opcional per l'enllaç", max_length=255, null=True, verbose_name="Títol pel botó de l'enllaç"),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='boton_texto_google_form_ca',
            field=models.CharField(blank=True, help_text="Títol pel botó de l'enllaç opcional per l'enllaç", max_length=255, null=True, verbose_name="Títol pel botó de l'enllaç"),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='boton_texto_google_form_en',
            field=models.CharField(blank=True, help_text="Títol pel botó de l'enllaç opcional per l'enllaç", max_length=255, null=True, verbose_name="Títol pel botó de l'enllaç"),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='boton_texto_google_form_es',
            field=models.CharField(blank=True, help_text="Títol pel botó de l'enllaç opcional per l'enllaç", max_length=255, null=True, verbose_name="Títol pel botó de l'enllaç"),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='boton_texto_google_form_fr',
            field=models.CharField(blank=True, help_text="Títol pel botó de l'enllaç opcional per l'enllaç", max_length=255, null=True, verbose_name="Títol pel botó de l'enllaç"),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='titulo_google_form',
            field=models.CharField(blank=True, help_text='Títol pel enllaç opcional pel formulari', max_length=255, null=True, verbose_name='Títol pel enllaç'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='titulo_google_form_ca',
            field=models.CharField(blank=True, help_text='Títol pel enllaç opcional pel formulari', max_length=255, null=True, verbose_name='Títol pel enllaç'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='titulo_google_form_en',
            field=models.CharField(blank=True, help_text='Títol pel enllaç opcional pel formulari', max_length=255, null=True, verbose_name='Títol pel enllaç'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='titulo_google_form_es',
            field=models.CharField(blank=True, help_text='Títol pel enllaç opcional pel formulari', max_length=255, null=True, verbose_name='Títol pel enllaç'),
        ),
        migrations.AddField(
            model_name='eventoespecial',
            name='titulo_google_form_fr',
            field=models.CharField(blank=True, help_text='Títol pel enllaç opcional pel formulari', max_length=255, null=True, verbose_name='Títol pel enllaç'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='link_google_form',
            field=models.URLField(blank=True, help_text='Enllaç opcional pel formulari', null=True),
        ),
    ]
