# Generated by Django 5.1.2 on 2025-10-08 19:49

import colorfield.fields
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0041_eventoespecial_boton_texto_google_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoespecial',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_corta',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_corta_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_corta_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_corta_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_corta_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descripció curta de l'esdeveniment especial", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_larga',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descripció llarga de l'esdeveniment especial", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_larga_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descripció llarga de l'esdeveniment especial", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_larga_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descripció llarga de l'esdeveniment especial", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_larga_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descripció llarga de l'esdeveniment especial", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AlterField(
            model_name='eventoespecial',
            name='descripcion_larga_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descripció llarga de l'esdeveniment especial", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Afegeix un missatge per l'esdeveniment", verbose_name='comentari'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Afegeix un missatge per l'esdeveniment", null=True, verbose_name='comentari'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido_en',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Afegeix un missatge per l'esdeveniment", null=True, verbose_name='comentari'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido_es',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Afegeix un missatge per l'esdeveniment", null=True, verbose_name='comentari'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Afegeix un missatge per l'esdeveniment", null=True, verbose_name='comentari'),
        ),
    ]
