# Generated by Django 3.2.19 on 2023-05-31 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 5, 31, 8, 5, 21, 294985, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2023, 5, 31, 1, 0, 21, 294985, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2023, 5, 31, 0, 0, 21, 294985, tzinfo=utc)),
        ),
    ]
