# Generated by Django 3.2.19 on 2023-05-31 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_post_tags'),
        ('agenda', '0006_auto_20230531_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='id',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='metadescripcion',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='metatitulo',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='modificado_por',
        ),
        migrations.AddField(
            model_name='agenda',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post'),
            preserve_default=False,
        ),
    ]
