# Generated by Django 3.2.19 on 2023-05-31 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0006_alter_imagen_archivo'),
        ('agenda', '0007_auto_20230531_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaGaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen')),
            ],
        ),
    ]
