# Generated by Django 3.2.19 on 2023-06-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_agendagaleriaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='tipo_evento',
            field=models.CharField(choices=[('musica', 'Música'), ('teatre', 'Teatre'), ('exposicio', 'Exposició'), ('cinema', 'Cinema'), ('dansa', 'Dansa'), ('altres', 'Altres (Otros)')], default='altres', help_text='Selecciona el tipo de evento', max_length=20),
        ),
    ]
