# Generated by Django 3.2.19 on 2023-06-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_agenda_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tipo_evento',
            field=models.CharField(choices=[('musica', 'Música'), ('teatre', 'Teatre'), ('exposicio', 'Exposició'), ('festes', 'festes'), ('cinema', 'Cinema'), ('dansa', 'Dansa'), ('visites_guiades', 'Visites guiades'), ('activitats_turistiques', 'Activitats turístiques'), ('altres', 'Altres (Otros)')], default='altres', help_text='Selecciona el tipo de evento', max_length=30),
        ),
    ]
