# Generated by Django 3.2.19 on 2023-06-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_mappoint_publicado'),
        ('multimedia_manager', '0007_video'),
        ('blog', '0054_alter_categoria_slug'),
        ('agenda', '0010_alter_agenda_tipo_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaGuidada',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracion', models.DurationField()),
                ('punto_inicio', models.CharField(max_length=255)),
                ('publico_recomendado', models.CharField(choices=[('nens', 'nens'), ('joves', 'Joves'), ('adults', 'Adults'), ('todos', 'totes')], default='todos', max_length=20)),
                ('agendas', models.ManyToManyField(blank=True, related_name='visitas_guiadas', to='agenda.Agenda')),
                ('mapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.mappoint')),
            ],
            options={
                'verbose_name': 'Visita Guiada',
                'verbose_name_plural': 'Visitas Guiadas',
            },
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='VisitaGuidadaGaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen')),
                ('visita_guidada', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agenda.visitaguidada')),
            ],
        ),
    ]
