# Generated by Django 3.2.19 on 2023-06-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_auto_20230612_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitaguidadagaleriaimagen',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='visitaguidadagaleriaimagen',
            name='visita_guidada',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo_evento',
            field=models.CharField(choices=[('musica', 'Música'), ('teatre', 'Teatre'), ('exposicio', 'Exposició'), ('festes', 'festes'), ('cinema', 'Cinema'), ('dansa', 'Dansa'), ('visites_guiades', 'Visites guiades'), ('activitats_turistiques', 'Activitats turístiques'), ('xerrades', 'xarrades'), ('altres', 'Altres (Otros)')], default='altres', help_text='Selecciona el tipo de evento', max_length=30),
        ),
        migrations.DeleteModel(
            name='AgendaGaleriaImagen',
        ),
        migrations.DeleteModel(
            name='VisitaGuidadaGaleriaImagen',
        ),
    ]
