# Generated by Django 4.2.2 on 2023-06-14 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_alter_agenda_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguidada',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(days=2), help_text='Duració de la visita (en format DD HH:MM:SS)'),
        ),
    ]
