# Generated by Django 4.2.2 on 2023-06-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_mappoint_icono'),
        ('blog', '0062_alter_post_titulo'),
        ('agenda', '0015_alter_visitaguidada_duracion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitaGuidada',
            new_name='VisitaGuiada',
        ),
    ]
