# Generated by Django 4.2.2 on 2023-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_ruta_enlace_natura_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='entradas',
            field=models.BooleanField(default=False, help_text='Hi ha entrades?'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
