# Generated by Django 4.2.2 on 2023-06-29 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_agenda_entradas_agenda_fecha_agenda_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
