# Generated by Django 4.2.2 on 2023-06-29 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_alter_agenda_fecha_alter_agenda_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
