# Generated by Django 4.2.2 on 2023-07-04 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0022_remove_visitaguiada_punto_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 9, 19, 26, 317620, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang'),
        ),
    ]
