# Generated by Django 4.2.2 on 2023-07-05 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0025_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 10, 53, 40, 346102, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang'),
        ),
    ]
