# Generated by Django 4.2.2 on 2023-07-17 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_mappoint_contenido_adicional'),
        ('agenda', '0039_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='ubicació', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicació', to='map.mappoint', verbose_name='ubicació'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 6, 31, 42, 247903, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang'),
        ),
    ]
