# Generated by Django 4.2.2 on 2023-07-17 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0041_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='hora',
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 11, 58, 30, 476075, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang'),
        ),
        migrations.CreateModel(
            name='VariationAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda')),
            ],
            options={
                'verbose_name': 'variació de agenda',
                'verbose_name_plural': 'variacions',
            },
        ),
    ]
