# Generated by Django 4.2.2 on 2023-07-17 13:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0042_remove_agenda_fecha_remove_agenda_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationagenda',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 13, 20, 43, 306889, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang'),
        ),
    ]
