# Generated by Django 4.2.2 on 2023-07-20 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0043_alter_variationagenda_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tipo_evento',
            field=models.CharField(choices=[('musica', 'Música'), ('teatre', 'Teatre'), ('exposicio', 'Exposició'), ('festes', 'festes'), ('cinema', 'Cinema'), ('dansa', 'Dansa'), ('visites_guiades', 'Visites guiades'), ('activitats_turistiques', 'Activitats turístiques'), ('xerrades', 'xerrades'), ('joves', 'joves'), ('altres', 'Altres (Otros)')], default='altres', help_text='Selecciona el tipo de evento', max_length=30),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 13, 14, 3, 260487, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang'),
        ),
    ]
