# Generated by Django 4.2.2 on 2023-07-25 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0044_alter_agenda_tipo_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 8, 1, 10, 0, 24, 282275, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang'),
        ),
    ]
