# Generated by Django 4.2.2 on 2023-07-25 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0047_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 8, 1, 13, 49, 55, 957840, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang'),
        ),
    ]
