# Generated by Django 4.2.2 on 2023-08-16 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0116_alter_ruta_options_alter_variationagenda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={},
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 9, 19, 41, 739926, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
