# Generated by Django 4.2.2 on 2023-11-10 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0208_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='valoracion',
            field=models.FloatField(blank=True, help_text='Valoració de la rutA', null=True, verbose_name='Valoració'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 19, 56, 33, 940651, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
