# Generated by Django 4.2.2 on 2023-11-17 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0225_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoTurismoSostenible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nom del certificat del certificat.', max_length=100, verbose_name='títol')),
                ('descripcion', models.TextField(blank=True, help_text='Afegeix una descripció pel certificat.', null=True, verbose_name='Descripció')),
                ('logo', models.ImageField(help_text='Afegeix un Logo pel certificat.', upload_to='logos_certificados/', verbose_name='Logo')),
                ('ods_relacionados', models.CharField(blank=True, choices=[('ods_1', 'Fi de la pobresa'), ('ods_2', 'Fam zero'), ('ods_3', 'Salut i benestar'), ('ods_4', 'Educació de qualitat'), ('ods_5', 'Igualtat de gènere'), ('ods_6', 'Aigua neta i sanejament'), ('ods_7', 'Energia assequible i no contaminant'), ('ods_8', 'Treball decent i creixement econòmic'), ('ods_9', 'Indústria, innovació i infraestructura'), ('ods_10', 'Reducció de les desigualtats'), ('ods_11', 'Ciutats i comunitats sostenibles'), ('ods_12', 'Consum i produccions responsables'), ('ods_13', 'Acció pel clima'), ('ods_14', 'Vida submarina'), ('ods_15', "Vida d'ecosistemes terrestres"), ('ods_16', 'Pau, justícia i institucions sòlides'), ('ods_17', 'Aliances per assolir els objectius'), ('altres', 'Altres')], help_text='Vincula amb el ODS que té relació el certificat', null=True, verbose_name='ODS relacionat')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
            },
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 9, 6, 47, 762097, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
