# Generated by Django 4.2.2 on 2023-11-17 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0226_certificadoturismosostenible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoturismosostenible',
            name='enlace_externo',
            field=models.URLField(blank=True, help_text='Enllaç extern', null=True, verbose_name='Enllaç extern'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 9, 16, 59, 30748, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
