# Generated by Django 4.2.2 on 2023-11-17 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0228_visitaguiada_certificados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='certificados',
            field=models.ManyToManyField(blank=True, help_text='Afegeix els certificats de turisme sostenible que fas servir per la visita guiada', to='agenda.certificadoturismosostenible', verbose_name='Certificat'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 9, 25, 51, 207818, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
