# Generated by Django 4.2.2 on 2023-11-22 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0229_alter_visitaguiada_certificados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='certificados',
            field=models.ManyToManyField(blank=True, help_text='Afegeix els certificats de turisme sostenible que fas servir per la visita guiada.', to='agenda.certificadoturismosostenible', verbose_name='Certificat'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 12, 22, 10, 832566, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
