# Generated by Django 4.2.2 on 2023-11-27 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0230_alter_visitaguiada_certificados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('cat', 'Català (fa-icon-for-catalan)'), ('es', 'Espanyol (fa-flag-spain)'), ('en', 'Anglès (fa-flag-usa)'), ('fr', 'Francès (fa-flag-france)'), ('it', 'Italià (fa-flag-italy)'), ('de', 'Alemany (fa-flag-germany)'), ('pt', 'Portuguès (fa-flag-portugal)'), ('ar', 'Àrab (fa-flag-saudi-arabia)'), ('fem', 'Feminista (fa-icon-for-feminista)'), ('fem_only', 'Només Dones (fa-icon-for-female-only)')], help_text="Nom de l'idioma PE: espanyol, català o altres com llenguatge inclusiu pels sords u/o altres llenguatges.", max_length=100, verbose_name="Nom de l'idioma.")),
                ('codigo', models.CharField(help_text="Afegeix un codi únic per identificar l'idioma.", max_length=10, unique=True, verbose_name='Codi')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomes',
            },
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 12, 4, 11, 33, 45, 419393, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
