# Generated by Django 4.2.2 on 2023-11-27 12:00

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0231_idioma_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció pels usuaris a la plantilla de l'agenda.", null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 12, 4, 12, 0, 17, 330404, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
