# Generated by Django 4.2.2 on 2023-11-27 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0232_idioma_descripcion_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='idiomas',
            field=models.ManyToManyField(blank=True, help_text="Idiomes que són disponibles per l'agenda.", related_name='idiomes', to='agenda.idioma', verbose_name='idiomes'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 12, 4, 14, 25, 43, 592988, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
