# Generated by Django 4.2.2 on 2023-11-30 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0233_agenda_idiomas_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='nombre',
            field=models.CharField(choices=[('cat', 'Català (fa-icon-for-catalan)'), ('es', 'Espanyol (fa-flag-spain)'), ('en', 'Anglès (fa-flag-usa)'), ('fr', 'Francès (fa-flag-france)'), ('it', 'Italià (fa-flag-italy)'), ('de', 'Alemany (fa-flag-germany)'), ('pt', 'Portuguès (fa-flag-portugal)'), ('ar', 'Àrab (fa-flag-saudi-arabia)'), ('fem', 'Feminista (fa-icon-for-feminista)'), ('au', 'autisme (fa-icon-for-autisme)'), ('inc', 'inclusiu (fa-icon-for-inc)')], help_text="Nom de l'idioma PE: espanyol, català o altres com llenguatge inclusiu pels sords u/o altres llenguatges.", max_length=100, verbose_name="Nom de l'idioma."),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2023, 12, 7, 14, 48, 42, 796551, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
