# Generated by Django 4.2.2 on 2024-01-16 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0018_alter_audio_options'),
        ('agenda', '0270_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 23, 14, 38, 0, 559431, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
        migrations.CreateModel(
            name='AudioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.audio', verbose_name='Àudio de la ruta')),
                ('ruta', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='agenda.ruta', verbose_name='Ruta')),
            ],
        ),
    ]
