# Generated by Django 4.2.2 on 2024-01-17 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0018_alter_audio_options'),
        ('agenda', '0271_alter_visitaguiada_fecha_fin_audioruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioruta',
            name='idioma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agenda.idioma', verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='audioruta',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.audio', verbose_name='Àudio de la ruta'),
        ),
        migrations.AlterField(
            model_name='audioruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.ruta', verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 14, 35, 11, 245334, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
