# Generated by Django 4.2.2 on 2024-01-17 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0272_audioruta_idioma_alter_audioruta_audio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioruta',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='audioruta',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 14, 45, 19, 967765, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
