# Generated by Django 4.2.2 on 2024-01-18 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0273_alter_audioruta_options_audioruta_orden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioruta',
            options={'ordering': ['orden'], 'verbose_name': 'Àudio', 'verbose_name_plural': 'Àudios'},
        ),
        migrations.RemoveField(
            model_name='audioruta',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='audioruta',
            name='ruta',
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 25, 14, 47, 7, 378563, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
        migrations.CreateModel(
            name='PlayListRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_intern', models.CharField(help_text='Afegiex un nom intern', max_length=100, verbose_name='nom intern')),
                ('idioma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agenda.idioma', verbose_name='Idioma')),
                ('ruta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agenda.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'PlayList',
                'verbose_name_plural': 'PlayList',
            },
        ),
        migrations.AddField(
            model_name='audioruta',
            name='playlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agenda.playlistruta', verbose_name='playlist'),
        ),
    ]
