# Generated by Django 4.2.2 on 2024-01-19 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0275_remove_playlistruta_ruta_ruta_playlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='playlist',
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 26, 7, 26, 0, 638024, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='playlist',
            field=models.ManyToManyField(blank=True, null=True, to='agenda.playlistruta', verbose_name='Playlist'),
        ),
    ]
