# Generated by Django 4.2.2 on 2024-01-22 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0277_alter_ruta_playlist_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioruta',
            name='link_uniquo',
            field=models.URLField(blank=True, help_text="Afegeix un enllaç 'https://gaudeixcabrera.cat/redirect/meu_fitxer.mp3'", null=True, unique=True, verbose_name='Afegeix un enllaç unic'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 29, 12, 48, 20, 634768, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
