# Generated by Django 4.2.2 on 2024-01-22 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0278_audioruta_link_uniquo_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioruta',
            old_name='link_uniquo',
            new_name='link_unico',
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 29, 13, 59, 0, 787434, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
