# Generated by Django 4.2.2 on 2024-01-24 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0281_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistruta',
            options={'ordering': ['orden'], 'verbose_name': 'PlayList', 'verbose_name_plural': 'PlayList'},
        ),
        migrations.AddField(
            model_name='playlistruta',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 11, 9, 26, 943040, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
