# Generated by Django 4.2.2 on 2024-01-24 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0282_alter_playlistruta_options_playlistruta_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='playlist',
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 11, 18, 4, 571962, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.playlistruta', verbose_name='Playlist'),
        ),
    ]
