# Generated by Django 4.2.2 on 2024-01-24 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0283_remove_ruta_playlist_alter_visitaguiada_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlistruta',
            name='ruta',
            field=models.ForeignKey(blank=True, help_text='ruta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruta', to='agenda.ruta', verbose_name='ruta'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 11, 22, 49, 117856, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
