# Generated by Django 4.2.2 on 2024-01-24 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0284_remove_ruta_playlist_playlistruta_ruta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistruta',
            name='ruta',
        ),
        migrations.AddField(
            model_name='ruta',
            name='playlist',
            field=models.ManyToManyField(blank=True, to='agenda.playlistruta', verbose_name='Playlist'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 11, 24, 52, 216915, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
