# Generated by Django 4.2.2 on 2024-01-29 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0288_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='descripcion_corta_ca',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='descripcion_corta_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='descripcion_corta_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 13, 14, 33, 732562, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
