# Generated by Django 4.2.2 on 2024-02-01 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0293_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='actividad_ca',
            field=models.CharField(blank=True, help_text='Activitat de la ruta', max_length=255, null=True, verbose_name='Activitat'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='actividad_en',
            field=models.CharField(blank=True, help_text='Activitat de la ruta', max_length=255, null=True, verbose_name='Activitat'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='actividad_es',
            field=models.CharField(blank=True, help_text='Activitat de la ruta', max_length=255, null=True, verbose_name='Activitat'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='dificultad_ca',
            field=models.CharField(choices=[('facil', 'Fàcil'), ('media', 'Mitjana'), ('dificil', 'Difícil')], default='facil', help_text='Dificultat de la ruta', max_length=20, null=True, verbose_name='Dificultat'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='dificultad_en',
            field=models.CharField(choices=[('facil', 'Fàcil'), ('media', 'Mitjana'), ('dificil', 'Difícil')], default='facil', help_text='Dificultat de la ruta', max_length=20, null=True, verbose_name='Dificultat'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='dificultad_es',
            field=models.CharField(choices=[('facil', 'Fàcil'), ('media', 'Mitjana'), ('dificil', 'Difícil')], default='facil', help_text='Dificultat de la ruta', max_length=20, null=True, verbose_name='Dificultat'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tema_ca',
            field=models.CharField(blank=True, help_text='Tema de la ruta', max_length=255, null=True, verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tema_en',
            field=models.CharField(blank=True, help_text='Tema de la ruta', max_length=255, null=True, verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tema_es',
            field=models.CharField(blank=True, help_text='Tema de la ruta', max_length=255, null=True, verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipologia_ca',
            field=models.CharField(choices=[('circular', 'Circular'), ('antihorario', 'Antihorari')], default='circular', help_text='Tipologia de la ruta', max_length=20, null=True, verbose_name='Tipologia'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipologia_en',
            field=models.CharField(choices=[('circular', 'Circular'), ('antihorario', 'Antihorari')], default='circular', help_text='Tipologia de la ruta', max_length=20, null=True, verbose_name='Tipologia'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipologia_es',
            field=models.CharField(choices=[('circular', 'Circular'), ('antihorario', 'Antihorari')], default='circular', help_text='Tipologia de la ruta', max_length=20, null=True, verbose_name='Tipologia'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 7, 27, 27, 335841, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
