# Generated by Django 4.2.2 on 2024-02-06 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0091_subcategoria_descripcion_ca_and_more'),
        ('agenda', '0296_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('tipo', models.CharField(choices=[('hotel', 'Hotel'), ('alberg', 'Alberg'), ('turístic', 'Allotjament turístic'), ('autocaravanes', 'Autocaravanes')], max_length=20, verbose_name="Tipus d'Allotjament")),
                ('direccion', models.CharField(help_text='Afegeix la dirrecció del allotjament', max_length=255, verbose_name='Direcció')),
                ('telefono', models.CharField(blank=True, help_text='Afegeix el telefón principal', max_length=20, null=True, verbose_name='Telefon')),
                ('sitio_web', models.URLField(blank=True, help_text="Afegix el lloc web de l'empresa", null=True, verbose_name='Lloc web')),
                ('capacidad', models.IntegerField(help_text='Máxim de persones.', verbose_name='Capacitat')),
                ('horarios', models.TextField(help_text='Horaris de obertura i tancament', verbose_name='Horaris')),
                ('google_maps_link', models.URLField(blank=True, help_text="Afegeix l'enllaç cap a Google Maps.", null=True, verbose_name='Enllaç del Google Maps')),
                ('latitud', models.FloatField(blank=True, help_text="Aquest Camp es opcional, si no l'afegeixes no es generarà el map.", null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, help_text="Aquest Camp es opcional, si no l'afegeixes no es generarà el map.", null=True, verbose_name='Longitud')),
                ('pet_friendly', models.BooleanField(default=False, verbose_name='Pet Friendly')),
                ('wifi', models.BooleanField(default=False, verbose_name='WiFi')),
            ],
            options={
                'verbose_name': 'allotjament',
                'verbose_name_plural': 'allotjaments',
            },
            bases=('blog.post',),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 2, 13, 8, 21, 33, 120701, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
