# Generated by Django 4.2.2 on 2024-02-06 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0299_alojamiento_adaptado_movilidad_reducida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='horarios',
            field=models.TextField(blank=True, help_text='Horaris de obertura i tancament', null=True, verbose_name='Horaris'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 2, 13, 10, 25, 2, 65147, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
