# Generated by Django 4.2.2 on 2024-02-07 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0092_alter_categoria_tipo'),
        ('agenda', '0300_alter_alojamiento_horarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('tipo', models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('masia', 'Masia'), ('guingueta', 'guingueta')], max_length=20, verbose_name='Tipus de restaurant')),
                ('direccion', models.CharField(help_text='Afegeix la dirrecció del allotjament', max_length=255, verbose_name='Direcció')),
                ('telefono', models.CharField(blank=True, help_text='Afegeix el telefón principal', max_length=20, null=True, verbose_name='Telefon')),
                ('sitio_web', models.URLField(blank=True, help_text="Afegix el lloc web de l'empresa", null=True, verbose_name='Lloc web')),
                ('capacidad', models.IntegerField(help_text='Máxim de persones.', verbose_name='Capacitat')),
                ('horarios', models.TextField(blank=True, help_text='Horaris de obertura i tancament', null=True, verbose_name='Horaris')),
                ('google_maps_link', models.URLField(blank=True, help_text="Afegeix l'enllaç cap a Google Maps.", null=True, verbose_name='Enllaç del Google Maps')),
                ('latitud', models.FloatField(blank=True, help_text="Aquest Camp es opcional, si no l'afegeixes no es generarà el map.", null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, help_text="Aquest Camp es opcional, si no l'afegeixes no es generarà el map.", null=True, verbose_name='Longitud')),
                ('pet_friendly', models.BooleanField(default=False, help_text='Indica si el restaurant admet mascotes.', verbose_name='Admet mascotes')),
                ('opciones_vegetarianas', models.BooleanField(default=False, help_text='Indica si el restaurant ofereix opcions vegetarianes.', verbose_name='Opcions vegetarianes')),
                ('wifi', models.BooleanField(default=False, help_text='Indica si el restaurant ofereix WiFi als clients.', verbose_name='WiFi disponible')),
                ('apto_para_celiacos', models.BooleanField(default=False, help_text='Indica si el restaurant ofereix opcions per a celíacs.', verbose_name='Apte per a celíacs')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
            },
            bases=('blog.post',),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 2, 14, 12, 28, 46, 338146, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
