# Generated by Django 4.2.2 on 2024-02-08 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0303_restaurante_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='descripcion_corta_ca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='descripcion_corta_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='descripcion_corta_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 2, 15, 7, 31, 16, 192390, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
