# Generated by Django 4.2.2 on 2024-02-08 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0304_restaurante_descripcion_corta_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='menu_infantil',
            field=models.BooleanField(default=False, help_text='Indica si el restaurant ofereix menú infantil.', verbose_name='Menú infantil'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='terraza',
            field=models.BooleanField(default=False, help_text='Indica si el restaurant disposa de terrassa.', verbose_name='Terrassa disponible'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 2, 15, 9, 0, 46, 561495, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
