# Generated by Django 4.2.2 on 2024-02-12 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0305_restaurante_menu_infantil_restaurante_terraza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='accessibilitat',
            field=models.BooleanField(default=False, help_text='Indica si el restaurant compta amb accessibilitat per a persones amb discapacitat.', verbose_name='Accessibilitat per a persones amb discapacitat'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='parking',
            field=models.BooleanField(default=False, help_text='Indica si el restaurant compta amb estacionament o aparcament.', verbose_name='Aparcament'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='capacidad',
            field=models.IntegerField(blank=True, help_text='Máxim de persones.', null=True, verbose_name='Capacitat'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 2, 19, 8, 58, 36, 284581, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
