# Generated by Django 4.2.2 on 2024-03-06 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0354_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='duracion',
            field=models.DurationField(blank=True, help_text='Durada de la ruta.PE 00:02:30(DD:HH:MM)', null=True, verbose_name='Durada'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 10, 45, 40, 220328, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
