# Generated by Django 4.2.2 on 2024-04-06 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0377_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='descripcion_corta_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='descripcion_corta_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='actividad_fr',
            field=models.CharField(blank=True, help_text='Activitat de la ruta', max_length=255, null=True, verbose_name='Activitat'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='dificultad_fr',
            field=models.CharField(choices=[('facil', 'Fàcil'), ('media', 'Mitjana'), ('dificil', 'Difícil')], default='facil', help_text='Dificultat de la ruta', max_length=20, null=True, verbose_name='Dificultat'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tema_fr',
            field=models.CharField(blank=True, help_text='Tema de la ruta', max_length=255, null=True, verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipologia_fr',
            field=models.CharField(choices=[('circular', 'Circular'), ('antihorario', 'Antihorari')], default='circular', help_text='Tipologia de la ruta', max_length=20, null=True, verbose_name='Tipologia'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 4, 13, 20, 40, 28, 558862, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
