# Generated by Django 4.2.2 on 2024-04-10 07:31

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0099_alter_categoria_tipo'),
        ('agenda', '0380_alter_visitaguiada_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imatge que surtirà a un costat de la descripció', upload_to='vision_mision/', verbose_name='imatge')),
                ('descripcion', ckeditor.fields.RichTextField(help_text='Descripció que surtirá al costat de la imatge', verbose_name='descripció')),
                ('descripcion_ca', ckeditor.fields.RichTextField(help_text='Descripció que surtirá al costat de la imatge', null=True, verbose_name='descripció')),
                ('descripcion_en', ckeditor.fields.RichTextField(help_text='Descripció que surtirá al costat de la imatge', null=True, verbose_name='descripció')),
                ('descripcion_es', ckeditor.fields.RichTextField(help_text='Descripció que surtirá al costat de la imatge', null=True, verbose_name='descripció')),
                ('descripcion_fr', ckeditor.fields.RichTextField(help_text='Descripció que surtirá al costat de la imatge', null=True, verbose_name='descripció')),
                ('orden', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Visió/Misió',
                'verbose_name_plural': 'Visions/Misions',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 4, 17, 7, 31, 18, 469509, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
        migrations.CreateModel(
            name='TurismeSostenible',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('misions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.visionmision', verbose_name='Misió i Visió')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.post',),
        ),
    ]
