# Generated by Django 4.2.2 on 2024-04-10 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0381_visionmision_alter_visitaguiada_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turismesostenible',
            name='misions',
        ),
        migrations.AddField(
            model_name='visionmision',
            name='turisme_sostenible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.turismesostenible', verbose_name='Turisme Sostenible relacionat'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 4, 17, 8, 33, 18, 127066, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
