# Generated by Django 4.2.2 on 2024-04-10 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0382_remove_turismesostenible_misions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visionmision',
            options={'ordering': ['orden'], 'verbose_name': 'bones pràctiques', 'verbose_name_plural': 'bones pràctiques'},
        ),
        migrations.AddField(
            model_name='visionmision',
            name='titulo',
            field=models.CharField(blank=True, help_text='Afegeix el títol', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='visionmision',
            name='titulo_ca',
            field=models.CharField(blank=True, help_text='Afegeix el títol', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='visionmision',
            name='titulo_en',
            field=models.CharField(blank=True, help_text='Afegeix el títol', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='visionmision',
            name='titulo_es',
            field=models.CharField(blank=True, help_text='Afegeix el títol', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='visionmision',
            name='titulo_fr',
            field=models.CharField(blank=True, help_text='Afegeix el títol', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 4, 17, 11, 1, 57, 978429, tzinfo=datetime.timezone.utc), help_text='Data de finalització del rang', verbose_name='Data de finalització'),
        ),
    ]
