# Generated by Django 4.2.2 on 2024-04-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0383_alter_visionmision_options_visionmision_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitaguiada',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='visitaguiada',
            name='fecha_inicio',
        ),
        migrations.CreateModel(
            name='FechaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Dada de la visita guiada.')),
                ('visita_guiada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='agenda.visitaguiada')),
            ],
        ),
    ]
