# Generated by Django 4.2.2 on 2024-04-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0384_remove_visitaguiada_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechavisita',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterModelOptions(
            name='turismesostenible',
            options={'verbose_name': 'Turisme sostenible', 'verbose_name_plural': 'Turisme sostenible'},
        ),
        migrations.AddField(
            model_name='turismesostenible',
            name='titulo_auxiliar_buenas_practicas',
            field=models.CharField(blank=True, help_text="Afegeix el títol auxiliar per l'aside de bones pràctiques", max_length=255, null=True, verbose_name='Títol auxiliar'),
        ),
        migrations.AddField(
            model_name='turismesostenible',
            name='titulo_auxiliar_buenas_practicas_ca',
            field=models.CharField(blank=True, help_text="Afegeix el títol auxiliar per l'aside de bones pràctiques", max_length=255, null=True, verbose_name='Títol auxiliar'),
        ),
        migrations.AddField(
            model_name='turismesostenible',
            name='titulo_auxiliar_buenas_practicas_en',
            field=models.CharField(blank=True, help_text="Afegeix el títol auxiliar per l'aside de bones pràctiques", max_length=255, null=True, verbose_name='Títol auxiliar'),
        ),
        migrations.AddField(
            model_name='turismesostenible',
            name='titulo_auxiliar_buenas_practicas_es',
            field=models.CharField(blank=True, help_text="Afegeix el títol auxiliar per l'aside de bones pràctiques", max_length=255, null=True, verbose_name='Títol auxiliar'),
        ),
        migrations.AddField(
            model_name='turismesostenible',
            name='titulo_auxiliar_buenas_practicas_fr',
            field=models.CharField(blank=True, help_text="Afegeix el títol auxiliar per l'aside de bones pràctiques", max_length=255, null=True, verbose_name='Títol auxiliar'),
        ),
    ]
