# Generated by Django 4.2.2 on 2024-04-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0385_alter_fechavisita_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='pdfs_auxiliares/')),
                ('titulo', models.CharField(max_length=255, verbose_name='Títol')),
                ('titulo_ca', models.CharField(max_length=255, null=True, verbose_name='Títol')),
                ('titulo_en', models.CharField(max_length=255, null=True, verbose_name='Títol')),
                ('titulo_es', models.CharField(max_length=255, null=True, verbose_name='Títol')),
                ('titulo_fr', models.CharField(max_length=255, null=True, verbose_name='Títol')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripció')),
                ('descripcion_ca', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('descripcion_en', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('descripcion_es', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('descripcion_fr', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('orden', models.IntegerField(default=0, help_text="Defineix l'ordre de visualització dels PDFs", verbose_name='Ordre')),
                ('turisme_sostenible', models.ForeignKey(help_text='Selecciona el turisme sostenible al qual aquest PDF està associat', on_delete=django.db.models.deletion.CASCADE, related_name='pdfs_auxiliares', to='agenda.turismesostenible', verbose_name='Turisme Sostenible associat')),
            ],
            options={
                'verbose_name': 'PDF Auxiliar',
                'verbose_name_plural': 'PDFs Auxiliars',
                'ordering': ['orden'],
            },
        ),
    ]
