# Generated by Django 4.2.2 on 2024-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0386_pdfauxiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismesostenible',
            name='titulo_auxiliar_pdf',
            field=models.CharField(blank=True, help_text="Afegeix el títol auxiliar per l'aside del PDF", max_length=255, null=True, verbose_name='Títol auxiliar PDF'),
        ),
    ]
