# Generated by Django 4.2.2 on 2024-04-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0387_turismesostenible_titulo_auxiliar_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismesostenible',
            name='titulo_auxiliar_pdf_ca',
            field=models.CharField(blank=True, help_text="Afegeix el títol auxiliar per l'aside del PDF", max_length=255, null=True, verbose_name='Títol auxiliar PDF'),
        ),
        migrations.AddField(
            model_name='turismesostenible',
            name='titulo_auxiliar_pdf_en',
            field=models.CharField(blank=True, help_text="Afegeix el títol auxiliar per l'aside del PDF", max_length=255, null=True, verbose_name='Títol auxiliar PDF'),
        ),
        migrations.AddField(
            model_name='turismesostenible',
            name='titulo_auxiliar_pdf_es',
            field=models.CharField(blank=True, help_text="Afegeix el títol auxiliar per l'aside del PDF", max_length=255, null=True, verbose_name='Títol auxiliar PDF'),
        ),
        migrations.AddField(
            model_name='turismesostenible',
            name='titulo_auxiliar_pdf_fr',
            field=models.CharField(blank=True, help_text="Afegeix el títol auxiliar per l'aside del PDF", max_length=255, null=True, verbose_name='Títol auxiliar PDF'),
        ),
    ]
