# Generated by Django 4.2.2 on 2024-04-12 11:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0388_turismesostenible_titulo_auxiliar_pdf_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismesostenible',
            name='color_impar',
            field=colorfield.fields.ColorField(default='#000000', help_text='Selecciona el color per als elements senars.', image_field=None, max_length=18, samples=None, verbose_name='Color per a elements senars'),
        ),
        migrations.AddField(
            model_name='turismesostenible',
            name='color_par',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Selecciona el color per als elements parells.', image_field=None, max_length=18, samples=None, verbose_name='Color per a elements parells'),
        ),
    ]
