# Generated by Django 4.2.2 on 2024-04-25 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0389_turismesostenible_color_impar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(seconds=18000), help_text='Duració de la visita (en format HH:MM:SS)', verbose_name='Duració'),
        ),
    ]
