# Generated by Django 4.2.2 on 2024-04-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0390_alter_visitaguiada_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='valoracion',
        ),
    ]
