# Generated by Django 4.2.2 on 2024-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0391_remove_ruta_duracion_remove_ruta_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='duracion',
            field=models.DurationField(blank=True, help_text='Durada de la ruta.PE 00:02:30(DD:HH:MM)', null=True, verbose_name='Durada'),
        ),
    ]
