# Generated by Django 5.1.2 on 2025-10-08 19:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0392_ruta_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turismesostenible',
            name='color_impar',
            field=colorfield.fields.ColorField(default='#000000', help_text='Selecciona el color per als elements senars.', image_field=None, max_length=25, samples=None, verbose_name='Color per a elements senars'),
        ),
        migrations.AlterField(
            model_name='turismesostenible',
            name='color_par',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Selecciona el color per als elements parells.', image_field=None, max_length=25, samples=None, verbose_name='Color per a elements parells'),
        ),
    ]
