# Generated by Django 4.2.2 on 2023-12-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos_especiales', '0032_alter_mensaje_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interno', models.CharField(help_text='Afegeix un nom especial per poder descriure millor la teva Newsletter', max_length=200, verbose_name='nom intern')),
                ('html_file', models.FileField(blank=True, null=True, upload_to='newsletters/')),
                ('evento_especial', models.ForeignKey(help_text="Afegeix l'esdeveniment que vols", on_delete=django.db.models.deletion.CASCADE, to='eventos_especiales.eventoespecial', verbose_name='Esdeveniment especial')),
            ],
            options={
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
