# Generated by Django 4.2.2 on 2023-12-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='link_tracking',
            field=models.URLField(blank=True, help_text="afegeix l'ellaç per fer tracking. També l'enllaç té que portar una redirecció cap a la web de Gaudeix", null=True, verbose_name='enllaç per fer tracking'),
        ),
    ]
