# Generated by Django 4.2.2 on 2023-12-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_link_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subtitulo',
            field=models.TextField(blank=True, help_text="afegeix un subtìtul o el nom de l'esdeveniment PE: 'Festa del Nadal'.", null=True, verbose_name='subtìtul'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='link_tracking',
            field=models.URLField(blank=True, help_text="afegeix l'ellaç per fer tracking. També l'enllaç té que portar una redirecció cap a la web de Gaudeix.", null=True, verbose_name='enllaç per fer tracking.'),
        ),
    ]
