# Generated by Django 4.2.2 on 2024-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter_subtitulo_alter_newsletter_link_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='html_file',
            field=models.FileField(blank=True, editable=False, help_text='Aquest fitxer es genera des del llistat de newsletter.', null=True, upload_to='newsletters/', verbose_name='Plantilla HTML.'),
        ),
    ]
