# Generated by Django 4.2.2 on 2024-02-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_alter_newsletter_html_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subtitulo_ca',
            field=models.TextField(blank=True, help_text="afegeix un subtìtul o el nom de l'esdeveniment PE: 'Festa del Nadal'.", null=True, verbose_name='subtìtul'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subtitulo_en',
            field=models.TextField(blank=True, help_text="afegeix un subtìtul o el nom de l'esdeveniment PE: 'Festa del Nadal'.", null=True, verbose_name='subtìtul'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subtitulo_es',
            field=models.TextField(blank=True, help_text="afegeix un subtìtul o el nom de l'esdeveniment PE: 'Festa del Nadal'.", null=True, verbose_name='subtìtul'),
        ),
    ]
