# Generated by Django 4.2.2 on 2024-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_newsletter_subtitulo_ca_newsletter_subtitulo_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='html_file_ca',
            field=models.FileField(blank=True, editable=False, help_text='Aquest fitxer es genera des del llistat de newsletter.', null=True, upload_to='newsletters/', verbose_name='Plantilla HTML.'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='html_file_en',
            field=models.FileField(blank=True, editable=False, help_text='Aquest fitxer es genera des del llistat de newsletter.', null=True, upload_to='newsletters/', verbose_name='Plantilla HTML.'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='html_file_es',
            field=models.FileField(blank=True, editable=False, help_text='Aquest fitxer es genera des del llistat de newsletter.', null=True, upload_to='newsletters/', verbose_name='Plantilla HTML.'),
        ),
    ]
