# Generated by Django 4.2.2 on 2024-04-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_newsletter_html_file_ca_newsletter_html_file_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='html_file_fr',
            field=models.FileField(blank=True, editable=False, help_text='Aquest fitxer es genera des del llistat de newsletter.', null=True, upload_to='newsletters/', verbose_name='Plantilla HTML.'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subtitulo_fr',
            field=models.TextField(blank=True, help_text="afegeix un subtìtul o el nom de l'esdeveniment PE: 'Festa del Nadal'.", null=True, verbose_name='subtìtul'),
        ),
    ]
