# Generated by Django 4.2.1 on 2023-05-16 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(100)])),
                ('descripcion_corta_movil', models.CharField(max_length=50)),
                ('icono', models.CharField(max_length=100)),
                ('enlace_externo', models.URLField()),
            ],
        ),
    ]
