# Generated by Django 4.2.1 on 2023-05-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topbar',
            name='icono',
        ),
    ]
