# Generated by Django 4.2 on 2023-05-25 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0002_remove_topbar_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='descripcion',
            field=models.TextField(help_text='Descripció del TopBar', validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='descripcion_corta_movil',
            field=models.CharField(blank=True, help_text='Descripció curta per a mòbils', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='enlace_externo',
            field=models.URLField(blank=True, help_text='Enllaç extern', null=True),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='titulo',
            field=models.CharField(help_text='Títol del TopBar', max_length=100),
        ),
    ]
