# Generated by Django 4.2 on 2023-05-25 10:18

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0003_topbar_publicado_alter_topbar_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='fondo',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Color de fons del TopBar', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='topbar',
            name='texto_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Color del text del TopBar', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Indica si el TopBar està publicat'),
        ),
    ]
