# Generated by Django 4.2 on 2023-05-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0004_topbar_fondo_topbar_texto_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='titulo_extermo',
            field=models.URLField(blank=True, help_text='nom enllaç', null=True),
        ),
    ]
