# Generated by Django 4.2 on 2023-05-25 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0005_topbar_titulo_extermo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topbar',
            name='titulo_extermo',
        ),
        migrations.AddField(
            model_name='topbar',
            name='titulo_externo',
            field=models.TextField(blank=True, help_text='nom enllaç', null=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
