# Generated by Django 4.2 on 2023-05-25 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0008_alter_topbar_titulo_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='descripcion',
            field=models.TextField(help_text='Descripció del TopBar', validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
