# Generated by Django 3.2.19 on 2023-05-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0009_alter_topbar_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='titulo_externo',
            field=models.CharField(blank=True, help_text='nom enllaç màxim 20 paraules', max_length=25, null=True),
        ),
    ]
