# Generated by Django 4.2.2 on 2023-09-14 13:15

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0010_alter_topbar_titulo_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='descripcion',
            field=models.TextField(help_text='Descripció del TopBar', validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Descripció del TopBar'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='descripcion_corta_movil',
            field=models.CharField(blank=True, help_text='Descripció curta per a mòbils', max_length=50, null=True, verbose_name='Descripció curta per a mòbils'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='enlace_externo',
            field=models.URLField(blank=True, help_text='Enllaç extern', null=True, verbose_name='Enllaç extern'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='fondo',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Color de fons del TopBar', image_field=None, max_length=18, samples=None, verbose_name='Color de fons del TopBar'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Indica si el TopBar està publicat', verbose_name='TopBar publicat'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='texto_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Color del text del TopBar', image_field=None, max_length=18, samples=None, verbose_name='Color del text del TopBar'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='titulo',
            field=models.CharField(help_text='Títol del TopBar', max_length=100, verbose_name='Títol del TopBar'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='titulo_externo',
            field=models.CharField(blank=True, help_text='nom enllaç màxim 20 paraules', max_length=25, null=True, verbose_name='Nom enllaç'),
        ),
    ]
