# Generated by Django 4.2.2 on 2024-02-14 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0011_alter_topbar_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='descripcion_ca',
            field=models.TextField(help_text='Descripció del TopBar', null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Descripció del TopBar'),
        ),
        migrations.AddField(
            model_name='topbar',
            name='descripcion_corta_movil_ca',
            field=models.CharField(blank=True, help_text='Descripció curta per a mòbils', max_length=50, null=True, verbose_name='Descripció curta per a mòbils'),
        ),
        migrations.AddField(
            model_name='topbar',
            name='descripcion_corta_movil_en',
            field=models.CharField(blank=True, help_text='Descripció curta per a mòbils', max_length=50, null=True, verbose_name='Descripció curta per a mòbils'),
        ),
        migrations.AddField(
            model_name='topbar',
            name='descripcion_corta_movil_es',
            field=models.CharField(blank=True, help_text='Descripció curta per a mòbils', max_length=50, null=True, verbose_name='Descripció curta per a mòbils'),
        ),
        migrations.AddField(
            model_name='topbar',
            name='descripcion_en',
            field=models.TextField(help_text='Descripció del TopBar', null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Descripció del TopBar'),
        ),
        migrations.AddField(
            model_name='topbar',
            name='descripcion_es',
            field=models.TextField(help_text='Descripció del TopBar', null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Descripció del TopBar'),
        ),
        migrations.AddField(
            model_name='topbar',
            name='titulo_ca',
            field=models.CharField(help_text='Títol del TopBar', max_length=100, null=True, verbose_name='Títol del TopBar'),
        ),
        migrations.AddField(
            model_name='topbar',
            name='titulo_en',
            field=models.CharField(help_text='Títol del TopBar', max_length=100, null=True, verbose_name='Títol del TopBar'),
        ),
        migrations.AddField(
            model_name='topbar',
            name='titulo_es',
            field=models.CharField(help_text='Títol del TopBar', max_length=100, null=True, verbose_name='Títol del TopBar'),
        ),
    ]
