# Generated by Django 4.2.2 on 2024-02-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0012_topbar_descripcion_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='titulo_externo_ca',
            field=models.CharField(blank=True, help_text='nom enllaç màxim 20 paraules', max_length=25, null=True, verbose_name='Nom enllaç'),
        ),
        migrations.AddField(
            model_name='topbar',
            name='titulo_externo_en',
            field=models.CharField(blank=True, help_text='nom enllaç màxim 20 paraules', max_length=25, null=True, verbose_name='Nom enllaç'),
        ),
        migrations.AddField(
            model_name='topbar',
            name='titulo_externo_es',
            field=models.CharField(blank=True, help_text='nom enllaç màxim 20 paraules', max_length=25, null=True, verbose_name='Nom enllaç'),
        ),
    ]
