# Generated by Django 4.2.2 on 2024-02-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0013_topbar_titulo_externo_ca_topbar_titulo_externo_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='descripcion_corta_movil',
            field=models.CharField(blank=True, help_text='Descripció curta per a mòbils (màxim 50 paraules)', max_length=50, null=True, verbose_name='Descripció curta per a mòbils'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='descripcion_corta_movil_ca',
            field=models.CharField(blank=True, help_text='Descripció curta per a mòbils (màxim 50 paraules)', max_length=50, null=True, verbose_name='Descripció curta per a mòbils'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='descripcion_corta_movil_en',
            field=models.CharField(blank=True, help_text='Descripció curta per a mòbils (màxim 50 paraules)', max_length=50, null=True, verbose_name='Descripció curta per a mòbils'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='descripcion_corta_movil_es',
            field=models.CharField(blank=True, help_text='Descripció curta per a mòbils (màxim 50 paraules)', max_length=50, null=True, verbose_name='Descripció curta per a mòbils'),
        ),
    ]
