# Generated by Django 5.1.2 on 2025-10-08 19:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topbar', '0015_topbar_descripcion_corta_movil_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='fondo',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Color de fons del TopBar', image_field=None, max_length=25, samples=None, verbose_name='Color de fons del TopBar'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='texto_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Color del text del TopBar', image_field=None, max_length=25, samples=None, verbose_name='Color del text del TopBar'),
        ),
    ]
