# Generated by Django 4.2.1 on 2023-05-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teenvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'API Teenvio',
                'verbose_name_plural': 'API Teenvio',
            },
        ),
    ]
