# Generated by Django 4.2.1 on 2023-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teenvio',
            name='action',
        ),
        migrations.AddField(
            model_name='teenvio',
            name='url',
            field=models.URLField(default='https://master5.teenvio.com/v4/public/api/v3/post/'),
        ),
    ]
