# Generated by Django 4.2.1 on 2023-05-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_teenvio_action_teenvio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='teenvio',
            name='subscribers',
            field=models.ManyToManyField(related_name='newsletters', to='api.subscriptor'),
        ),
    ]
