# Generated by Django 4.2.1 on 2023-05-17 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subscriptor_teenvio_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
