# Generated by Django 4.2.1 on 2023-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscriptor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptor',
            name='exportable',
            field=models.BooleanField(default=True),
        ),
    ]
