# Generated by Django 4.2.2 on 2023-06-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_teenvio_subscribers_subscriptor_teenvio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptor',
            name='teenvio',
        ),
    ]
