# Generated by Django 4.2.2 on 2023-10-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_subscriptor_created_at_alter_subscriptor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_server', models.CharField(choices=[('mailtrap', 'mailtrap'), ('gmail', 'gmail')], default='gmail', help_text='Selecciona el servei de correu que vols que arribin els mails del formulari.', max_length=20, verbose_name='Servidor de correu')),
            ],
            options={
                'verbose_name': 'Servidor de correu',
                'verbose_name_plural': 'Servidor de correu',
            },
        ),
        migrations.CreateModel(
            name='Mailtrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='Nombre de usuario de Teenvio', max_length=100, verbose_name="Nom d'usuari de Teenvio")),
                ('password', models.CharField(help_text='Contraseña de Teenvio', max_length=100, verbose_name='contrasenya')),
            ],
            options={
                'verbose_name': 'API Mailtrap',
                'verbose_name_plural': 'API Mailtrap',
            },
        ),
    ]
