# Generated by Django 4.2.2 on 2023-10-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mailmanager_mailtrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamilServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.EmailField(help_text='Correu electrònic del remitent', max_length=254, verbose_name='Correu electrònic del remitent')),
            ],
            options={
                'verbose_name': 'API GmailServer',
                'verbose_name_plural': 'API GmailServer',
            },
        ),
    ]
