# Generated by Django 4.2.2 on 2023-10-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_gamilserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmanager',
            name='gmail_server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.gamilserver', verbose_name='gmail'),
        ),
        migrations.AddField(
            model_name='mailmanager',
            name='mailtrap_server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.mailtrap', verbose_name='mailtrap'),
        ),
    ]
