# Generated by Django 4.2.2 on 2023-10-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mailmanager_gmail_server_mailmanager_mailtrap_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmanager',
            name='gmail_server',
        ),
        migrations.RemoveField(
            model_name='mailmanager',
            name='mailtrap_server',
        ),
        migrations.AddField(
            model_name='gamilserver',
            name='server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.mailmanager', verbose_name='MailManager'),
        ),
        migrations.AddField(
            model_name='mailtrap',
            name='mail_server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.mailmanager', verbose_name='MailManager'),
        ),
    ]
