# Generated by Django 4.2.2 on 2023-10-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_mailmanager_gmail_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='Nombre de usuario de Outlook', max_length=100, verbose_name="Nom d'usuari de Outlook")),
                ('password', models.CharField(help_text='Contraseña de Outlook', max_length=100, verbose_name='contrasenya')),
            ],
            options={
                'verbose_name': 'API outlook',
                'verbose_name_plural': 'API outlook',
            },
        ),
        migrations.AlterField(
            model_name='mailmanager',
            name='mail_server',
            field=models.CharField(choices=[('outlook', 'outlook'), ('gmail', 'gmail')], default='gmail', help_text='Selecciona el servei de correu que vols que arribin els mails del formulari.', max_length=20, verbose_name='Servidor de correu'),
        ),
        migrations.DeleteModel(
            name='Mailtrap',
        ),
        migrations.AddField(
            model_name='outlookserver',
            name='mail_server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.mailmanager', verbose_name='MailManager'),
        ),
    ]
