# Generated by Django 4.2.2 on 2023-10-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_outlookserver_alter_mailmanager_mail_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamilserver',
            name='recipient_email',
            field=models.EmailField(default='turisme@cabrerademar.cat', help_text='Correo electrónico del destinatario en Gmail', max_length=254, verbose_name='Correo electrónico del destinatario en Gmail'),
        ),
        migrations.AddField(
            model_name='outlookserver',
            name='recipient_email',
            field=models.EmailField(default='turisme@cabrerademar.cat', help_text='Correo electrónico del destinatario en Outlook', max_length=254, verbose_name='Correo electrónico del destinatario en Outlook'),
        ),
        migrations.AddField(
            model_name='outlookserver',
            name='smtp_server_port',
            field=models.PositiveIntegerField(default=587, help_text='Puerto del servidor SMTP de Outlook (por ejemplo, 587)'),
        ),
        migrations.AddField(
            model_name='outlookserver',
            name='smtp_server_url',
            field=models.CharField(default='smtp-mail.outlook.com', help_text='URL del servidor SMTP de Outlook (por ejemplo, smtp.office365.com)', max_length=100),
        ),
        migrations.AddField(
            model_name='outlookserver',
            name='use_tls',
            field=models.BooleanField(default=True, help_text='Usar TLS para la conexión SMTP'),
        ),
    ]
