# Generated by Django 4.2.2 on 2024-01-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multimedia_manager', '0016_alter_parallax_titulo_alter_videosembed_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Introdueix el títol de l'alerta", max_length=200, verbose_name='títol')),
                ('descripcion', models.TextField(help_text="Escriu una descripció detallada de l'alerta", verbose_name='descripció')),
                ('fecha_inicio', models.DateTimeField(help_text="Selecciona quan comença l'alerta", verbose_name="data d'inici")),
                ('fecha_fin', models.DateTimeField(help_text="Selecciona quan finalitza l'alerta", verbose_name='data de finalització')),
                ('imagen', models.ForeignKey(help_text="Puja una imatge relacionada amb l'alerta (opcional)", on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='imatge')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertes',
            },
        ),
    ]
