# Generated by Django 4.2.2 on 2024-01-11 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='descripcion',
            field=models.TextField(help_text="Escriu una descripció detallada de l'alerta", max_length=25, validators=[django.core.validators.MaxLengthValidator(25)], verbose_name='descripció'),
        ),
    ]
