# Generated by Django 4.2.2 on 2024-01-11 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0002_alter_alerta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='descripcion',
            field=models.TextField(help_text="Escriu una descripció detallada de l'alerta", max_length=255, validators=[django.core.validators.MaxLengthValidator(255)], verbose_name='descripció'),
        ),
    ]
