# Generated by Django 4.2.2 on 2024-01-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0003_alter_alerta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicat'),
        ),
    ]
