# Generated by Django 4.2.2 on 2024-01-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0004_alerta_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='publicado',
            field=models.BooleanField(default=False, help_text="Marca si l'alerta està activa", verbose_name='Publicat'),
        ),
    ]
