# Generated by Django 4.2.2 on 2024-01-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0016_alter_parallax_titulo_alter_videosembed_titulo'),
        ('alerta', '0005_alter_alerta_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='fichero',
            field=models.OneToOneField(blank=True, help_text='Afegeix un fitxer pdf.', null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero', verbose_name='Fitxer'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='ver_mas',
            field=models.URLField(blank=True, help_text="Afegeix un enllaç per donar més informació de l'alerta. (opcional)", null=True, verbose_name='Enllaç'),
        ),
    ]
