# Generated by Django 4.2.2 on 2024-01-12 09:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0006_alerta_fichero_alerta_ver_mas'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', help_text="Selecciona un color pel disseny de l'alerta.", image_field=None, max_length=18, samples=None, verbose_name='Color'),
        ),
    ]
