# Generated by Django 4.2.2 on 2024-04-06 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0008_alerta_descripcion_ca_alerta_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='descripcion_fr',
            field=models.TextField(help_text="Escriu una descripció detallada de l'alerta", max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)], verbose_name='descripció'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='titulo_fr',
            field=models.CharField(help_text="Introdueix el títol de l'alerta", max_length=200, null=True, verbose_name='títol'),
        ),
    ]
