# Generated by Django 5.1.2 on 2025-10-08 19:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0009_alerta_descripcion_fr_alerta_titulo_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', help_text="Selecciona un color pel disseny de l'alerta.", image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
    ]
