# Generated by Django 4.2.2 on 2023-11-03 18:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_utils', '0002_remove_registroerror_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroerror',
            options={'verbose_name': "Registre d'errors.", 'verbose_name_plural': "Registre d'errors."},
        ),
        migrations.AlterField(
            model_name='registroerror',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Traceback del problema'),
        ),
        migrations.AlterField(
            model_name='registroerror',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='registroerror',
            name='nota',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Explicació de l'error i la seva solució", null=True, verbose_name='Notes del problema'),
        ),
        migrations.AlterField(
            model_name='registroerror',
            name='resuelto',
            field=models.BooleanField(default=False, verbose_name='Resolt'),
        ),
        migrations.AlterField(
            model_name='registroerror',
            name='titulo',
            field=models.TextField(editable=False, null=True, verbose_name='Títol'),
        ),
    ]
