# Generated by Django 4.2.2 on 2023-09-26 16:08

import ckeditor.fields
import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalizacion', '0027_remove_videosembed_videos_videosembed_video_and_more'),
        ('blog', '0079_alter_categoria_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia_manager', '0013_fichero_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDescubre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol')),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció')),
                ('titulo', models.CharField(help_text='Títol pel compra i descobreix. PE: Compra i descobreix 2023', max_length=255, verbose_name='Títol')),
                ('slug', models.SlugField(editable=False, help_text='Slug automàtic generat a partir del títol', unique=True)),
                ('primary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Color primari')),
                ('secondary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Color secondary')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, help_text="Data de l'esdeveniment Compra i descobreix", verbose_name="Data de l'esdeveniment")),
                ('fecha_fin', models.DateField(default=django.utils.timezone.now, help_text="Data de finalització de l'esdeveniment Compra i descobreix", verbose_name='Data de finalització')),
                ('publicado', models.BooleanField(default=False, help_text="Indica si l'esdeveniment especial està publicat", verbose_name='Publicat')),
                ('descripcion_larga', ckeditor.fields.RichTextField(blank=True, help_text="Descripció llarga de l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció llarga')),
                ('descripcion_corta', ckeditor.fields.RichTextField(blank=True, help_text="Descripció curta de l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció curta')),
                ('agendas', models.ManyToManyField(blank=True, help_text="Selecciona tots els esdeveniments vinculats amb l'event Compra i descobreix", to='blog.post', verbose_name='esdeveniment Compra i descobreix')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parallax', models.ForeignKey(blank=True, help_text="Parallax relacionat amb l'esdeveniment Compra i descobreix (opcional)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.parallax', verbose_name='Parallax')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Esdeveniments Especials Compra i descubre',
            },
        ),
        migrations.CreateModel(
            name='CompraDescubreImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compadescubre', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='compra_y_descubre.compradescubre', verbose_name='CompraDescubre')),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='Imatge')),
            ],
        ),
        migrations.CreateModel(
            name='CompaDescubrePasosImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Títol pel compra i descobreix. PE: Pas 2A. Format paper', max_length=255, verbose_name='Títol')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, help_text="Descripció del pas l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció curta')),
                ('compadescubre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='compra_y_descubre.compradescubre')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='CompaDescubreFichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compradescubre', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='compra_y_descubre.compradescubre')),
                ('fichero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero')),
            ],
        ),
    ]
