# Generated by Django 4.2.2 on 2023-09-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradescubre',
            name='comerciante',
            field=models.URLField(blank=True, help_text='Afegeix el link per els comerciants', verbose_name='Comerciant'),
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='participante',
            field=models.URLField(blank=True, help_text='Afegeix el link per els participants', verbose_name='Participant'),
        ),
    ]
