# Generated by Django 4.2.2 on 2023-09-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_mappoint_enlace_google_maps_alter_mappoint_calle_and_more'),
        ('compra_y_descubre', '0002_compradescubre_comerciante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compradescubre',
            name='agendas',
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='negocis',
            field=models.ManyToManyField(blank=True, help_text="Selecciona tots els comerços vinculats amb l'event Compra i descobreix", to='map.mappoint', verbose_name='Comerços Compra i descobreix'),
        ),
    ]
