# Generated by Django 4.2.2 on 2023-10-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0013_fichero_titulo'),
        ('compra_y_descubre', '0004_remove_compradescubre_parallax'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadComprayParticipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Títol per l'entitat compra i descobreix. PE: La mer", max_length=255, verbose_name='Títol')),
                ('enllaç', models.URLField(blank=True, help_text="Afegeix el link de la fitxa per l'entitat ", verbose_name='Comerciant')),
            ],
            options={
                'verbose_name_plural': 'Esdeveniments Especials Compra i descubre',
            },
        ),
        migrations.RenameModel(
            old_name='CompaDescubreFichero',
            new_name='CompraDescubreFichero',
        ),
        migrations.RenameModel(
            old_name='CompaDescubrePasosImagen',
            new_name='CompraDescubrePasosImagen',
        ),
        migrations.RenameField(
            model_name='compradescubreimagen',
            old_name='compadescubre',
            new_name='compradescubre',
        ),
        migrations.RenameField(
            model_name='compradescubrepasosimagen',
            old_name='compadescubre',
            new_name='compradescubre',
        ),
        migrations.CreateModel(
            name='CompraDescubreGaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compradescubre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='compra_y_descubre.compradescubre')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen')),
            ],
        ),
        migrations.AlterField(
            model_name='compradescubre',
            name='negocis',
            field=models.ManyToManyField(blank=True, help_text="Selecciona tots els comerços vinculats amb l'event Compra i descobreix", to='compra_y_descubre.entidadcomprayparticipa', verbose_name='Comerços Compra i descobreix'),
        ),
    ]
