# Generated by Django 4.2.2 on 2023-10-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0005_entidadcomprayparticipa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradescubre',
            old_name='negocis',
            new_name='entidades',
        ),
    ]
