# Generated by Django 4.2.2 on 2023-10-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0006_rename_negocis_compradescubre_entidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compradescubre',
            name='entidades',
        ),
    ]
