# Generated by Django 4.2.2 on 2023-10-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0007_remove_compradescubre_entidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradescubre',
            name='entidades',
            field=models.ManyToManyField(blank=True, help_text="Selecciona tots els comerços vinculats amb l'event Compra i descobreix", to='compra_y_descubre.entidadcomprayparticipa', verbose_name='Comerços Compra i descobreix'),
        ),
    ]
