# Generated by Django 4.2.2 on 2023-10-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0008_compradescubre_entidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidadcomprayparticipa',
            options={'verbose_name_plural': 'Entitats'},
        ),
    ]
