# Generated by Django 4.2.2 on 2023-10-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0009_alter_entidadcomprayparticipa_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidadcomprayparticipa',
            old_name='enllaç',
            new_name='enllace',
        ),
    ]
