# Generated by Django 4.2.2 on 2023-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0010_rename_enllaç_entidadcomprayparticipa_enllace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compradescubregaleriaimagen',
            options={'verbose_name_plural': "Galeria dels guanyadors de l'esdeveniment 'compra i descobreix'."},
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='sorteo',
            field=models.URLField(blank=True, help_text='Afegeix el link del sorteig', verbose_name='sorteix'),
        ),
    ]
