# Generated by Django 4.2.2 on 2023-10-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0011_alter_compradescubregaleriaimagen_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compradescubre',
            options={'verbose_name': "Esdeveniment Especial 'Compra i descubre'.", 'verbose_name_plural': "Esdeveniments Especials 'Compra i descubre'."},
        ),
        migrations.AlterModelOptions(
            name='entidadcomprayparticipa',
            options={'verbose_name': 'Entitat', 'verbose_name_plural': 'Entitats'},
        ),
    ]
