# Generated by Django 4.2.2 on 2023-10-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0012_alter_compradescubre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compradescubre',
            options={'verbose_name': "Esdeveniment Especial 'Compra i descobreix'.", 'verbose_name_plural': "Esdeveniments Especials 'Compra i descobreix'."},
        ),
    ]
