# Generated by Django 4.2.2 on 2023-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0013_alter_compradescubre_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradescubre',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR'),
        ),
    ]
