# Generated by Django 4.2.2 on 2024-02-16 11:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0015_alter_compradescubre_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradescubre',
            name='descripcion_corta_ca',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció curta de l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='descripcion_corta_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció curta de l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='descripcion_corta_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció curta de l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='descripcion_larga_ca',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció llarga de l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='descripcion_larga_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció llarga de l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='descripcion_larga_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció llarga de l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció llarga'),
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='titulo_ca',
            field=models.CharField(help_text='Títol pel compra i descobreix. PE: Compra i descobreix 2023', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='titulo_en',
            field=models.CharField(help_text='Títol pel compra i descobreix. PE: Compra i descobreix 2023', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='compradescubre',
            name='titulo_es',
            field=models.CharField(help_text='Títol pel compra i descobreix. PE: Compra i descobreix 2023', max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
