# Generated by Django 4.2.2 on 2024-02-16 14:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0016_compradescubre_descripcion_corta_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradescubrepasosimagen',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció del pas l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='compradescubrepasosimagen',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció del pas l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='compradescubrepasosimagen',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Descripció del pas l'esdeveniment Compra i descobreix", null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='compradescubrepasosimagen',
            name='titulo_ca',
            field=models.CharField(help_text='Títol pel compra i descobreix. PE: Pas 2A. Format paper', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='compradescubrepasosimagen',
            name='titulo_en',
            field=models.CharField(help_text='Títol pel compra i descobreix. PE: Pas 2A. Format paper', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='compradescubrepasosimagen',
            name='titulo_es',
            field=models.CharField(help_text='Títol pel compra i descobreix. PE: Pas 2A. Format paper', max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
