# Generated by Django 4.2.2 on 2024-03-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0017_compradescubrepasosimagen_descripcion_ca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compradescubre',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': "Esdeveniment Especial 'Compra i descobreix'.", 'verbose_name_plural': "Esdeveniments Especials 'Compra i descobreix'."},
        ),
    ]
