# Generated by Django 5.1.2 on 2025-10-08 19:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_descubre', '0019_compradescubre_descripcion_corta_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradescubre',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color primari'),
        ),
        migrations.AlterField(
            model_name='compradescubre',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color secondary'),
        ),
    ]
