# Generated by Django 4.2.1 on 2023-05-15 13:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='categoria/ficheros/')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='categoria/galeria/')),
            ],
        ),
        migrations.AlterField(
            model_name='subblog',
            name='contenido',
            field=ckeditor.fields.RichTextField(help_text='Contenido del subblog'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='categoria/imagenes/')),
                ('meta_titulo', models.CharField(blank=True, max_length=255)),
                ('meta_descripcion', models.TextField(blank=True)),
                ('ficheros', models.ManyToManyField(blank=True, to='blog.fichero')),
                ('imagenes', models.ManyToManyField(blank=True, to='blog.galeriaimagen')),
                ('subblog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subblog')),
            ],
        ),
    ]
