# Generated by Django 4.2.1 on 2023-05-16 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_fichero_galeriaimagen_alter_subblog_contenido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='ficheros',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='fichero',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ficheros', to='blog.categoria'),
        ),
        migrations.AddField(
            model_name='galeriaimagen',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='blog.categoria'),
        ),
    ]
