# Generated by Django 4.2.1 on 2023-05-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_galeriaimagenpost_alter_fichero_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
