# Generated by Django 4.2.1 on 2023-05-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_fecha_post_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subblog',
            name='abrir_en_nueva_ventana',
        ),
        migrations.RemoveField(
            model_name='subblog',
            name='abrir_en_pespana',
        ),
    ]
