# Generated by Django 4.2.1 on 2023-05-17 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_remove_subblog_abrir_en_nueva_ventana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subblog',
            name='color',
        ),
        migrations.RemoveField(
            model_name='subblog',
            name='link',
        ),
        migrations.AddField(
            model_name='subblog',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subblogs_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subblog',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='subblog',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='subblog',
            name='modificado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subblog',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Indica si el subblog está publicado'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del subblog', null=True, upload_to='blog/subblogs/'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
