# Generated by Django 4.2.1 on 2023-05-17 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_remove_subblog_color_remove_subblog_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subblog',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subblogs_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
