# Generated by Django 4.2.1 on 2023-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_subblog_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subblog',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripción para SEO', null=True),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítulo para SEO', max_length=255, null=True),
        ),
    ]
