# Generated by Django 4.2.1 on 2023-05-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia_manager', '0001_initial'),
        ('blog', '0009_alter_subblog_metadescripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subblog',
            name='contenido',
            field=models.TextField(help_text='Contenido del subblog'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subblogs', to='multimedia_manager.imagen'),
        ),
    ]
