# Generated by Django 4.2.1 on 2023-05-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_subblog_contenido_alter_subblog_creado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subblog',
            name='imagen',
        ),
    ]
