# Generated by Django 4.2.1 on 2023-05-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0001_initial'),
        ('blog', '0013_remove_subblog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='subblog',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subblogs', to='multimedia_manager.imagen'),
        ),
    ]
