# Generated by Django 4.2.1 on 2023-05-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0001_initial'),
        ('blog', '0014_subblog_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subblog',
            name='imagen',
        ),
        migrations.CreateModel(
            name='SubBlogImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen')),
                ('subblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subblog')),
            ],
        ),
    ]
