# Generated by Django 4.2.1 on 2023-05-18 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia_manager', '0002_alter_imagen_archivo'),
        ('blog', '0017_alter_subblogimagen_subblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen_principal',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='meta_descripcion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='meta_titulo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripción para SEO', null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítulo para SEO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='modificado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CategoriaBannerImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.subblog')),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen')),
            ],
        ),
    ]
