# Generated by Django 4.2.1 on 2023-05-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0002_alter_imagen_archivo'),
        ('blog', '0018_remove_categoria_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagenes',
            field=models.ManyToManyField(related_name='galería', to='multimedia_manager.imagen'),
        ),
        migrations.DeleteModel(
            name='GaleriaImagen',
        ),
    ]
