# Generated by Django 4.2.1 on 2023-05-18 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0002_alter_imagen_archivo'),
        ('blog', '0019_categoria_imagenes_delete_galeriaimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriabannerimagen',
            name='categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.categoria'),
        ),
        migrations.CreateModel(
            name='CategoriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen')),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagenes',
            field=models.ManyToManyField(related_name='galería', to='blog.categoriaimagen'),
        ),
    ]
