# Generated by Django 4.2.1 on 2023-05-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_categoriabannerimagen_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='categoriaimagen',
            name='categoria',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria'),
        ),
    ]
