# Generated by Django 4.2.1 on 2023-05-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_rename_categoriaimagen_categoriagaleriaimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriagaleriaimagen',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria'),
        ),
    ]
