# Generated by Django 4.2 on 2023-05-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_categoriagaleriaimagen_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subblogimagen',
            name='subblog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.subblog'),
        ),
    ]
