# Generated by Django 4.2 on 2023-05-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_subblogimagen_subblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subblogimagen',
            name='subblog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subblog'),
        ),
    ]
