# Generated by Django 4.2 on 2023-05-19 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_subblogimagen_subblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Data de modificació'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='contenido',
            field=models.TextField(help_text='Contingut del subblog'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Data de modificació'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Indica si el subblog està publicat'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='titulo',
            field=models.CharField(help_text='Títol del subblog', max_length=100),
        ),
    ]
