# Generated by Django 4.2 on 2023-05-19 08:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subblog',
            name='contenido',
            field=ckeditor.fields.RichTextField(help_text='Contingut del subblog'),
        ),
    ]
