# Generated by Django 4.2 on 2023-05-19 08:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_subblog_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=ckeditor.fields.RichTextField(help_text='Descripció de categoría'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='subblog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.subblog'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='subtitulo',
            field=models.CharField(help_text='Subtítol de categoria', max_length=255),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(help_text='Títol de categoría', max_length=255),
        ),
    ]
