# Generated by Django 4.2 on 2023-05-19 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_categoria_descripcion_alter_categoria_subblog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='Color en formato hexadecimal (#RRGGBB)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Ingrese un código hexadecimal válido.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='categoria',
            name='especial',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Sí')], default=False, verbose_name='Categoría Especial'),
        ),
    ]
