# Generated by Django 4.2 on 2023-05-19 09:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_categoria_color_categoria_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
