# Generated by Django 4.2 on 2023-05-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0005_fichero'),
        ('blog', '0032_alter_categoriabannerimagen_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero')),
            ],
        ),
        migrations.CreateModel(
            name='PostGaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='PostImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen')),
            ],
        ),
        migrations.RemoveField(
            model_name='galeriaimagenpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen_interior',
        ),
        migrations.DeleteModel(
            name='Fichero',
        ),
        migrations.DeleteModel(
            name='GaleriaImagenPost',
        ),
        migrations.AddField(
            model_name='postimagen',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='postgaleriaimagen',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='postfichero',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
