# Generated by Django 4.2 on 2023-05-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_categoriagaleriaimagen_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriagaleriaimagen',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria'),
        ),
    ]
