# Generated by Django 4.2 on 2023-05-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_categoriagaleriaimagen_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='color',
        ),
        migrations.AddField(
            model_name='post',
            name='entradas',
            field=models.BooleanField(default=False, help_text='Hi ha entrades?'),
        ),
        migrations.AddField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postgaleriaimagen',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
