# Generated by Django 4.2 on 2023-05-22 10:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_remove_post_color_post_entradas_post_publicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=ckeditor.fields.RichTextField(help_text='Descripció de Post'),
        ),
    ]
