# Generated by Django 4.2 on 2023-05-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_subblog_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
