# Generated by Django 4.2 on 2023-05-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_categoria_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Indica si la categoria està publicada o no. Si està publicada, es mostrarà en la llista de categories disponibles.'),
        ),
    ]
