# Generated by Django 3.2.19 on 2023-06-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_alter_post_slug'),
    ]

    operations = [
    ]
