# Generated by Django 3.2.19 on 2023-06-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_auto_20230607_1135'),
    ]

    operations = [
    ]
