# Generated by Django 4.2.2 on 2023-06-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_noticia_creado_por_noticia_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='modificado_por',
        ),
        migrations.AddField(
            model_name='noticia',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True),
        ),
    ]
