# Generated by Django 4.2.2 on 2023-06-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_remove_noticia_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(help_text='Aquest camp està limitat per un màxim de 50 caràcters', max_length=200),
        ),
    ]
