# Generated by Django 4.2.2 on 2023-06-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_alter_categoria_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='entradas',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hora',
        ),
    ]
