# Generated by Django 4.2.2 on 2023-07-27 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
