# Generated by Django 4.2.2 on 2023-07-27 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_alter_tag_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nombre',
            field=models.CharField(help_text='Títol del tag', max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
