# Generated by Django 4.2.2 on 2023-08-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0011_alter_video_archivo'),
        ('blog', '0067_alter_tag_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubblogGaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen')),
                ('subblog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.subblog')),
            ],
        ),
    ]
