# Generated by Django 4.2.2 on 2023-08-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0068_subbloggaleriaimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('normal', 'normal'), ('agenda', 'agenda'), ('visitas_guiadas', 'visitas guiadas'), ('senderisme', 'senderisme'), ('noticies', 'noticies'), ('lloc', 'lloc'), ('festes_i_tradicions', 'festes i tradicions')], default='normal', max_length=20),
        ),
    ]
