# Generated by Django 4.2.2 on 2023-08-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Model de metadades', 'verbose_name_plural': 'Models de metadades'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Model de metadades', 'verbose_name_plural': 'Models de metadades'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Model de metadades', 'verbose_name_plural': 'Models de metadades'},
        ),
        migrations.AlterModelOptions(
            name='subblog',
            options={'verbose_name': 'Model de metadades', 'verbose_name_plural': 'Models de metadades'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol'),
        ),
        migrations.AlterField(
            model_name='post',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció'),
        ),
        migrations.AlterField(
            model_name='post',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='metadescripcion',
            field=models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='metatitulo',
            field=models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol'),
        ),
    ]
