# Generated by Django 4.2.2 on 2023-08-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0070_alter_categoria_options_alter_noticia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subblog',
            options={},
        ),
    ]
