# Generated by Django 4.2.2 on 2023-08-16 10:50

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_alter_categoria_options_alter_noticia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetes'},
        ),
        migrations.AlterField(
            model_name='subblog',
            name='contenido',
            field=ckeditor.fields.RichTextField(help_text='Contingut del subblog', verbose_name='Contingut'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Indica si el subblog està publicat', verbose_name='Publicat'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='titulo',
            field=models.CharField(help_text='Títol del subblog', max_length=100, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nombre',
            field=models.CharField(help_text='Títol del tag', max_length=255, validators=[django.core.validators.MaxLengthValidator(255)], verbose_name='Nom'),
        ),
    ]
