# Generated by Django 4.2.2 on 2023-08-16 11:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0013_fichero_titulo'),
        ('blog', '0072_alter_tag_options_alter_subblog_contenido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=ckeditor.fields.RichTextField(help_text='Descripció de categoría', verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='especial',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Sí')], default=False, verbose_name='Categoria Especial'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Indica si la categoria està publicada o no. Si està publicada, es mostrarà en la llista de categories disponibles.', verbose_name='Publicat'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='subblog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.subblog', verbose_name='Subblog'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='subtitulo',
            field=models.CharField(help_text='Subtítol de categoria', max_length=255, verbose_name='Subtítol'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('normal', 'normal'), ('agenda', 'agenda'), ('visitas_guiadas', 'visitas guiadas'), ('senderisme', 'senderisme'), ('noticies', 'noticies'), ('lloc', 'lloc'), ('festes_i_tradicions', 'festes i tradicions')], default='normal', max_length=20, verbose_name='Tipus'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(help_text='Títol de categoría', max_length=255, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='subbloggaleriaimagen',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='Imatge de la Galeria'),
        ),
        migrations.AlterField(
            model_name='subbloggaleriaimagen',
            name='subblog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.subblog', verbose_name='SubBlog'),
        ),
        migrations.AlterField(
            model_name='subblogimagen',
            name='imagen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='Imatge'),
        ),
        migrations.AlterField(
            model_name='subblogimagen',
            name='subblog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subblog', verbose_name='SubBlog'),
        ),
    ]
