# Generated by Django 4.2.2 on 2023-08-16 13:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0013_fichero_titulo'),
        ('blog', '0073_alter_categoria_options_alter_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriabannerimagen',
            options={'verbose_name': 'Imatge de Banner de Categoria', 'verbose_name_plural': 'Imatges de Banner de Categoria'},
        ),
        migrations.AlterModelOptions(
            name='categoriagaleriaimagen',
            options={'verbose_name': 'Imatge de Galeria de Categoria', 'verbose_name_plural': 'Imatges de Galeria de Categoria'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postimagen',
            options={'verbose_name': "Imatge de l'Entrada del Bloc", 'verbose_name_plural': 'Imatges de les Entrades del Bloc'},
        ),
        migrations.AlterField(
            model_name='categoriabannerimagen',
            name='categoria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='categoriabannerimagen',
            name='imagen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='Imatge del Banner'),
        ),
        migrations.AlterField(
            model_name='categoriagaleriaimagen',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='categoriagaleriaimagen',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='Imatge de la Galeria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=ckeditor.fields.RichTextField(help_text='Descripció de Post', verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicat'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(help_text='Aquest camp està limitat per un màxim de 50 caràcters', max_length=200, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='postimagen',
            name='imagen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='Imatge'),
        ),
        migrations.AlterField(
            model_name='postimagen',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Entrada del Bloc'),
        ),
    ]
