# Generated by Django 4.2.2 on 2023-08-17 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0013_fichero_titulo'),
        ('blog', '0074_alter_categoriabannerimagen_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Notícia'},
        ),
        migrations.AlterModelOptions(
            name='postgaleriaimagen',
            options={'verbose_name': "Galeria d'Imatges de l'Entrada del Bloc", 'verbose_name_plural': "Galeria d'Imatges de les Entrades del Bloc"},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(help_text='Contingut de la notícia', verbose_name='contingut'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data de la notícia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='Imatge URL'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Indica si la notícia està publicada', verbose_name='publicat'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(help_text='Títol de la notícia', max_length=200, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='postfichero',
            name='fichero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero', verbose_name='Fitxer'),
        ),
        migrations.AlterField(
            model_name='postfichero',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Entrada del Bloc'),
        ),
        migrations.AlterField(
            model_name='postgaleriaimagen',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='Imatge'),
        ),
        migrations.AlterField(
            model_name='postgaleriaimagen',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Entrada del Bloc'),
        ),
    ]
