# Generated by Django 4.2.2 on 2023-08-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_alter_noticia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícies'},
        ),
    ]
