# Generated by Django 4.2.2 on 2023-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_alter_noticia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subblog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tags'),
        ),
    ]
