# Generated by Django 4.2.2 on 2023-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0077_subblog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tags'),
        ),
    ]
