# Generated by Django 4.2.2 on 2023-09-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_categoria_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('normal', 'normal'), ('agenda', 'agenda'), ('visitas_guiadas', 'visitas guiadas'), ('senderisme', 'senderisme'), ('noticies', 'noticies'), ('lloc', 'lloc'), ('festes_i_tradicions', 'festes, tradicions i cultura')], default='normal', max_length=20, verbose_name='Tipus'),
        ),
    ]
