# Generated by Django 4.2.2 on 2023-10-06 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0079_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data de la notícia', verbose_name='Data de publicació.'),
        ),
    ]
