# Generated by Django 4.2.2 on 2024-01-12 14:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0080_alter_noticia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol')),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció')),
                ('titulo', models.CharField(help_text='Títol de la subcategoría', max_length=255, verbose_name='Títol')),
                ('descripcion', ckeditor.fields.RichTextField(help_text='Descripció de la subcategoría', verbose_name='Descripció')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='blog.categoria', verbose_name='Categoria')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subcategoria', verbose_name='SubCategoria'),
        ),
    ]
