# Generated by Django 4.2.2 on 2024-01-12 14:49

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0081_alter_post_categoria_subcategoria_post_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Indica si la categoria està publicada o no. Si està publicada, es mostrarà en la llista de categories disponibles.', verbose_name='Publicat'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tags'),
        ),
    ]
