# Generated by Django 4.2.2 on 2024-01-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0082_subcategoria_color_subcategoria_publicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Subtítol de categoria', max_length=255, null=True, verbose_name='Subtítol'),
        ),
    ]
