# Generated by Django 4.2.2 on 2024-01-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0084_subcategoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='tipo',
            field=models.CharField(choices=[('ruta_pel_patrimoni_historic', 'Ruta pel patrimoni històric'), ('ruta_en_bicicleta', 'Ruta pel patrimoni històric'), ('visitas_guiadas', 'visitas guiadas'), ('senderisme', 'senderisme'), ('itinerari_de_natura', 'Itinerari de Natura'), ('visita_al_castell_de_burriac', 'Visita al castell de Burriac'), ('normal', 'normal')], default='normal', max_length=50, verbose_name='Tipus'),
        ),
    ]
