# Generated by Django 4.2.2 on 2024-01-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0085_alter_subcategoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='tipo',
            field=models.CharField(choices=[('normal', 'normal'), ('visitas_guiadas', 'visitas guiadas'), ('senderisme', 'senderisme'), ('lloc', 'lloc'), ('festes_i_tradicions', 'festes, tradicions i cultura')], default='normal', max_length=50, verbose_name='Tipus'),
        ),
    ]
