# Generated by Django 4.2.2 on 2024-01-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0016_alter_parallax_titulo_alter_videosembed_titulo'),
        ('blog', '0086_alter_subcategoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoriaGaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='Imatge de la Galeria')),
                ('subcategoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.subcategoria', verbose_name='SubCategoria')),
            ],
            options={
                'verbose_name': 'Imatge de Galeria de la SubCategoria',
                'verbose_name_plural': 'Imatges de Galeria de les SubCategories',
            },
        ),
        migrations.CreateModel(
            name='SubCategoriaBannerImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='Imatge del Banner')),
                ('subcategoria', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subcategoria', verbose_name='SubCategoria')),
            ],
            options={
                'verbose_name': 'Imatge de Banner de la SubCategoria',
                'verbose_name_plural': 'Imatges de Banner de les SubCategories',
            },
        ),
    ]
