# Generated by Django 4.2.2 on 2024-01-29 11:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0087_subcategoriagaleriaimagen_subcategoriabannerimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(help_text='Descripció de Post', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(help_text='Descripció de Post', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(help_text='Descripció de Post', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo_ca',
            field=models.CharField(help_text='Aquest camp està limitat per un màxim de 50 caràcters', max_length=200, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo_en',
            field=models.CharField(help_text='Aquest camp està limitat per un màxim de 50 caràcters', max_length=200, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo_es',
            field=models.CharField(help_text='Aquest camp està limitat per un màxim de 50 caràcters', max_length=200, null=True, verbose_name='Títol'),
        ),
    ]
