# Generated by Django 4.2.2 on 2024-01-31 08:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0088_post_descripcion_ca_post_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subblog',
            name='contenido_ca',
            field=ckeditor.fields.RichTextField(help_text='Contingut del subblog', null=True, verbose_name='Contingut'),
        ),
        migrations.AddField(
            model_name='subblog',
            name='contenido_en',
            field=ckeditor.fields.RichTextField(help_text='Contingut del subblog', null=True, verbose_name='Contingut'),
        ),
        migrations.AddField(
            model_name='subblog',
            name='contenido_es',
            field=ckeditor.fields.RichTextField(help_text='Contingut del subblog', null=True, verbose_name='Contingut'),
        ),
        migrations.AddField(
            model_name='subblog',
            name='titulo_ca',
            field=models.CharField(help_text='Títol del subblog', max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='subblog',
            name='titulo_en',
            field=models.CharField(help_text='Títol del subblog', max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='subblog',
            name='titulo_es',
            field=models.CharField(help_text='Títol del subblog', max_length=100, null=True, verbose_name='Títol'),
        ),
    ]
