# Generated by Django 4.2.2 on 2024-01-31 10:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0089_subblog_contenido_ca_subblog_contenido_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(help_text='Descripció de categoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(help_text='Descripció de categoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(help_text='Descripció de categoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='subtitulo_ca',
            field=models.CharField(help_text='Subtítol de categoria', max_length=255, null=True, verbose_name='Subtítol'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='subtitulo_en',
            field=models.CharField(help_text='Subtítol de categoria', max_length=255, null=True, verbose_name='Subtítol'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='subtitulo_es',
            field=models.CharField(help_text='Subtítol de categoria', max_length=255, null=True, verbose_name='Subtítol'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='titulo_ca',
            field=models.CharField(help_text='Títol de categoría', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='titulo_en',
            field=models.CharField(help_text='Títol de categoría', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='titulo_es',
            field=models.CharField(help_text='Títol de categoría', max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
