# Generated by Django 4.2.2 on 2024-02-01 14:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0090_categoria_descripcion_ca_categoria_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(help_text='Descripció de la subcategoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(help_text='Descripció de la subcategoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(help_text='Descripció de la subcategoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='subtitulo_ca',
            field=models.CharField(blank=True, help_text='Subtítol de categoria', max_length=255, null=True, verbose_name='Subtítol'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='subtitulo_en',
            field=models.CharField(blank=True, help_text='Subtítol de categoria', max_length=255, null=True, verbose_name='Subtítol'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='subtitulo_es',
            field=models.CharField(blank=True, help_text='Subtítol de categoria', max_length=255, null=True, verbose_name='Subtítol'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='titulo_ca',
            field=models.CharField(help_text='Títol de la subcategoría', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='titulo_en',
            field=models.CharField(help_text='Títol de la subcategoría', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='titulo_es',
            field=models.CharField(help_text='Títol de la subcategoría', max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
