# Generated by Django 4.2.2 on 2024-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0093_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subblog',
            name='ver_mas',
            field=models.BooleanField(default=False, help_text="Indica si vols mostrar el botó 'Saber més'", verbose_name='saber més'),
        ),
    ]
