# Generated by Django 4.2.2 on 2024-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0094_subblog_ver_mas'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mostrar_primer_hijo',
            field=models.BooleanField(default=False, help_text='Indica si vols mostrar el primer element automàticament', verbose_name='Mostrar primer element'),
        ),
    ]
