# Generated by Django 4.2.2 on 2024-02-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0095_categoria_mostrar_primer_hijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='ver_mas',
            field=models.BooleanField(default=False, help_text="Indica si vols mostrar el botó 'Saber més'", verbose_name='saber més'),
        ),
    ]
