# Generated by Django 4.2.2 on 2024-02-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0096_categoria_ver_mas'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='mostrar_primer_hijo',
            field=models.BooleanField(default=False, help_text='Indica si vols mostrar el primer element automàticament, quan només tingui un fill publicat.', verbose_name='Mostrar primer element'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='mostrar_primer_hijo',
            field=models.BooleanField(default=False, help_text='Indica si vols mostrar el primer element automàticament, quan només tingui un fill publicat.', verbose_name='Mostrar primer element'),
        ),
    ]
