# Generated by Django 4.2.2 on 2024-04-06 20:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0097_subcategoria_mostrar_primer_hijo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion_fr',
            field=ckeditor.fields.RichTextField(help_text='Descripció de categoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='subtitulo_fr',
            field=models.CharField(help_text='Subtítol de categoria', max_length=255, null=True, verbose_name='Subtítol'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='titulo_fr',
            field=models.CharField(help_text='Títol de categoría', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion_fr',
            field=ckeditor.fields.RichTextField(help_text='Descripció de Post', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo_fr',
            field=models.CharField(help_text='Aquest camp està limitat per un màxim de 50 caràcters', max_length=200, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='subblog',
            name='contenido_fr',
            field=ckeditor.fields.RichTextField(help_text='Contingut del subblog', null=True, verbose_name='Contingut'),
        ),
        migrations.AddField(
            model_name='subblog',
            name='titulo_fr',
            field=models.CharField(help_text='Títol del subblog', max_length=100, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='descripcion_fr',
            field=ckeditor.fields.RichTextField(help_text='Descripció de la subcategoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='subtitulo_fr',
            field=models.CharField(blank=True, help_text='Subtítol de categoria', max_length=255, null=True, verbose_name='Subtítol'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='titulo_fr',
            field=models.CharField(help_text='Títol de la subcategoría', max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
