# Generated by Django 4.2.2 on 2024-04-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0098_categoria_descripcion_fr_categoria_subtitulo_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('normal', 'normal'), ('agenda', 'agenda'), ('visitas_guiadas', 'visitas guiadas'), ('senderisme', 'senderisme'), ('noticies', 'noticies'), ('lloc', 'lloc'), ('festes_i_tradicions', 'festes, tradicions i cultura'), ('allotjament', 'allotjament'), ('restaurant', 'restaurant'), ('turisme_sostenible', 'turisme sostenible')], default='normal', max_length=20, verbose_name='Tipus'),
        ),
    ]
