# Generated by Django 5.1.2 on 2025-10-08 19:49

import colorfield.fields
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0099_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de categoría', verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de categoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion_en',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de categoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion_es',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de categoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de categoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de Post', verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de Post', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion_en',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de Post', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion_es',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de Post', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de Post', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Contingut del subblog', verbose_name='Contingut'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='contenido_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Contingut del subblog', null=True, verbose_name='Contingut'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='contenido_en',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Contingut del subblog', null=True, verbose_name='Contingut'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='contenido_es',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Contingut del subblog', null=True, verbose_name='Contingut'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='contenido_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Contingut del subblog', null=True, verbose_name='Contingut'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de la subcategoría', verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de la subcategoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion_en',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de la subcategoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion_es',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de la subcategoría', null=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripció de la subcategoría', null=True, verbose_name='Descripció'),
        ),
    ]
