# Generated by Django 4.2.1 on 2023-05-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_sociales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='imagen',
            field=models.ImageField(help_text='Imagen del icono de la red social (dimensiones recomendadas: 32x32 pixels)', upload_to='redes_sociales'),
        ),
    ]
