# Generated by Django 4.2 on 2023-05-26 10:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redes_sociales', '0002_alter_redsocial_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocial',
            name='fondo',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Color de fons que vols', image_field=None, max_length=18, samples=None),
        ),
    ]
