# Generated by Django 4.2.2 on 2024-01-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redes_sociales', '0003_redsocial_fondo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redsocial',
            options={'verbose_name': 'xarxa social', 'verbose_name_plural': 'xarxes socials'},
        ),
    ]
