# Generated by Django 4.2.2 on 2024-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_sociales', '0004_alter_redsocial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redsocial',
            options={'ordering': ['orden'], 'verbose_name': 'xarxa social', 'verbose_name_plural': 'xarxes socials'},
        ),
        migrations.AddField(
            model_name='redsocial',
            name='orden',
            field=models.IntegerField(default=0, help_text="Defineix l'ordre de la xarxa social.", verbose_name='Ordre'),
        ),
    ]
