# Generated by Django 5.1.2 on 2025-10-08 19:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redes_sociales', '0005_alter_redsocial_options_redsocial_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='fondo',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Color de fons que vols', image_field=None, max_length=25, samples=None),
        ),
    ]
