"""
Django settings for gaudeix project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import json

BASE_LOCAL_DIR = Path(__file__).resolve().parent
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar la configuración desde el archivo config.json

config_file_path = os.path.join(BASE_LOCAL_DIR, 'config.json')
with open(config_file_path, 'r') as config_file:
    config = json.load(config_file)

# Cargar la configuración desde el archivo settings.json

settings_file_path = os.path.join(BASE_LOCAL_DIR, 'settings.json')
with open(settings_file_path, 'r') as settings_file:
    settings = json.load(settings_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings["DEBUG"]

ALLOWED_HOSTS = settings["ALLOWED_HOSTS"]


# Application definition

INSTALLED_APPS = [
    #'adminlteui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'dal',
    'dal_select2',
    #'taggit',
    'core',
    'bootstrap4',
    'blog',
    'redes_sociales',
    'topbar',
    'header',
    'api',
    'footer',
    'personalizacion',
    'multimedia_manager',
    'colorfield',
    'agenda',
    'paginas_estaticas',
    'eventos_especiales',
    'map',
    'fontawesomefree',
    'corsheaders',
    'imagekit',
    'embed_video',
    'compressor',
    'django_user_agents',
    'selecciones',
    'subvenciones',
    'compra_y_descubre'
    #'corsheaders',
    #'admin_tree'
    #'filters'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django_samesite_none.middleware.SameSiteNoneMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'gaudeix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'core', 'templates'),
            os.path.join(BASE_DIR, 'api', 'templates'),   # Directorio de plantillas de la aplicación api
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gaudeix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Base de datos
DATABASES = {
    'default': {
        'ENGINE': config["DATABASES"]["default"]["ENGINE"],
        'NAME': config["DATABASES"]["default"]["NAME"],
        'USER': config["DATABASES"]["default"]["USER"],
        'PASSWORD': config["DATABASES"]["default"]["PASSWORD"],
        'HOST': config["DATABASES"]["default"]["HOST"],
        'PORT': config["DATABASES"]["default"]["PORT"],
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = settings["LANGUAGE_CODE"]

DEFAULT_CHARSET = 'utf-8'

FILE_CHARSET = 'utf-8'


TIME_ZONE = settings["TIME_ZONE"]

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core/static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CKEDITOR_UPLOAD_PATH = 'uploads/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Ckeditor
CKEDITOR_CONFIGS = {
    'default': {
        'allowedContent': True,
    },
}


CKEDITOR_UPLOAD_PATH = "media/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

#GOOGLE_MAPS_API_KEY = 'kAIzaSyA7t0HCgOTtsO3whwMzARtjbO-cvkPIyyQ'

# Correo electrónico auxiliar
AUXILIARY_EMAIL = config['EMAIL_HOST_USER']
EMAIL_BACKEND = settings["EMAIL_BACKEND"]
EMAIL_HOST = settings["EMAIL_HOST"]
EMAIL_PORT = settings["EMAIL_PORT"]
EMAIL_USE_TLS = settings["EMAIL_USE_TLS"]
EMAIL_HOST_USER = config['EMAIL_HOST_USER']  # Reemplaza con tu dirección de correo Gmail
EMAIL_HOST_PASSWORD = config['EMAIL_HOST_PASSWORD'] # Reemplaza con tu contraseña de Gmail



CORS_ALLOW_ALL_ORIGINS = settings["CORS_ALLOW_ALL_ORIGINS"]
CORS_ALLOW_CREDENTIALS = settings["CORS_ALLOW_CREDENTIALS"]

CORS_ALLOW_METHODS = settings["CORS_ALLOW_METHODS"]

CORS_ALLOW_HEADERS = settings["CORS_ALLOW_HEADERS"]

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = settings["CSRF_COOKIE_SECURE"]


SESSION_COOKIE_SAMESITE = settings["SESSION_COOKIE_SAMESITE"]
CSRF_COOKIE_SAMESITE = settings["CSRF_COOKIE_SAMESITE"]

CORS_ALLOWED_ORIGINS = [
    "https://www.youtube.com",
]

# compresor

COMPRESS_ENABLED = settings["COMPRESS_ENABLED"]
COMPRESS_OFFLINE = settings["COMPRESS_OFFLINE"]

COMPRESS_CSS_FILTERS = [
    'compressor.filters.cssmin.CSSMinFilter',
]

COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter',
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

#cache
TIEMPO_EXPIRACION = 2 * 60 * 60



# Name of cache backend to cache user agents. If it not specified default
# cache alias will be used. Set to `None` to disable caching.
USER_AGENTS_CACHE = 'default'