# Generated by Django 4.2.2 on 2023-08-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0069_alter_categoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeleccionDestacados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Escriu un nom únic', max_length=100)),
                ('publicado', models.BooleanField(default=False, help_text='Marca si quieres que sea despublicado.')),
                ('coleccion', models.ManyToManyField(blank=True, related_name='seleccions', to='blog.post')),
            ],
        ),
    ]
