# Generated by Django 4.2.2 on 2023-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_especiales', '0008_remove_eventoespecial_imagenes_and_more'),
        ('selecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecciondestacados',
            name='eventos_especiales',
            field=models.ManyToManyField(blank=True, help_text='Selecciona els esdeveniments que vols que apareguin a la portada.', related_name='seleccio_especial', to='eventos_especiales.eventoespecial'),
        ),
        migrations.AlterField(
            model_name='selecciondestacados',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Marca si vols que estigui despublicat.'),
        ),
    ]
