# Generated by Django 4.2.2 on 2023-09-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0079_alter_categoria_tipo'),
        ('selecciones', '0002_selecciondestacados_eventos_especiales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecciondestacados',
            name='coleccion',
            field=models.ManyToManyField(blank=True, related_name='seleccions', to='blog.post', verbose_name='colecció'),
        ),
        migrations.AlterField(
            model_name='selecciondestacados',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Marca si vols que estigui despublicat.', verbose_name='Publicat'),
        ),
        migrations.AlterField(
            model_name='selecciondestacados',
            name='titulo',
            field=models.CharField(help_text='Escriu un nom únic', max_length=100, verbose_name='Títol'),
        ),
    ]
