# Generated by Django 4.2.1 on 2023-05-17 11:18

from django.db import migrations, models
import functools
import multimedia_manager.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('archivo', models.ImageField(blank=True, default=None, help_text='Extensiones permitidas: .jpg, .jpeg, .png, .gif, .bmp, .svg', null=True, upload_to=functools.partial(multimedia_manager.utils.generar_nombre_archivo, *(), **{'tipo': 'imagen'}))),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('fichero', 'Fichero')], default='imagen', editable=False, max_length=50)),
            ],
        ),
    ]
