# Generated by Django 4.2.1 on 2023-05-18 06:36

from django.db import migrations, models
import multimedia_manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='archivo',
            field=models.ImageField(blank=True, default=None, help_text='Extensiones permitidas: .jpg, .jpeg, .png, .gif, .bmp, .svg', null=True, upload_to=multimedia_manager.utils.upload_to_imagen),
        ),
    ]
