# Generated by Django 4.2 on 2023-05-18 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia_manager', '0002_alter_imagen_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagen',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='modificado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
