# Generated by Django 3.2.19 on 2023-05-31 08:38

from django.db import migrations, models
import multimedia_manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0005_fichero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='archivo',
            field=models.ImageField(default=None, help_text='Extensiones permitidas: .jpg, .jpeg, .png, .gif, .bmp, .svg', upload_to=multimedia_manager.utils.upload_to_imagen),
        ),
    ]
