# Generated by Django 4.2.2 on 2023-07-25 13:46

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0008_alter_video_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='archivo',
            field=embed_video.fields.EmbedVideoField(help_text='URL de YouTube o Vimeo'),
        ),
    ]
