# Generated by Django 4.2.2 on 2023-08-11 13:24

from django.db import migrations, models
import multimedia_manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0011_alter_video_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichero',
            name='archivo',
            field=models.FileField(blank=True, default=None, help_text='Extensiones permitidas: .pdf, .doc, .docx, .xls, .xlsx, .ppt, .pptx, .zip', null=True, upload_to=multimedia_manager.utils.upload_to_fichero),
        ),
    ]
