# Generated by Django 4.2.2 on 2023-10-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0013_fichero_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichero',
            options={'verbose_name': 'Fitxer', 'verbose_name_plural': 'Fitxers'},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'Imatge', 'verbose_name_plural': 'Imatges'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Vídeo', 'verbose_name_plural': 'vídeos'},
        ),
    ]
