# Generated by Django 4.2.2 on 2023-11-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0015_parallax_videosembed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallax',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Títola'),
        ),
        migrations.AlterField(
            model_name='videosembed',
            name='titulo',
            field=models.CharField(help_text='Títol del Vídeo.', max_length=100, verbose_name='Títola'),
        ),
    ]
