# Generated by Django 4.2.2 on 2024-01-16 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multimedia_manager.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia_manager', '0016_alter_parallax_titulo_alter_videosembed_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichero',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('fichero', 'Fichero'), ('audio', 'Audio')], default='fichero', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('fichero', 'Fichero'), ('audio', 'Audio')], default='imagen', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('fichero', 'Fichero'), ('audio', 'Audio')], default='video', editable=False, max_length=50),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('archivo', models.FileField(blank=True, default=None, help_text='Extensiones permitidas: .mp3, .wav, etc.', null=True, upload_to=multimedia_manager.utils.upload_to_audio)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('fichero', 'Fichero'), ('audio', 'Audio')], default='audio', editable=False, max_length=50)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
            },
        ),
    ]
