# Generated by Django 4.2.2 on 2024-01-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0017_alter_fichero_tipo_alter_imagen_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': 'Àudio', 'verbose_name_plural': 'Àudios'},
        ),
    ]
