# Generated by Django 4.2.2 on 2024-02-12 08:58

from django.db import migrations, models
import multimedia_manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0018_alter_audio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='archivo',
            field=models.ImageField(default=None, help_text='Extensiones permitidas: .jpg, .jpeg, .png, .gif, .bmp, .svg, webp', upload_to=multimedia_manager.utils.upload_to_imagen),
        ),
    ]
