# Generated by Django 4.2.2 on 2024-02-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0019_alter_imagen_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parallax',
            name='descripcion_corta_ca',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='parallax',
            name='descripcion_corta_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripció curta'),
        ),
        migrations.AddField(
            model_name='parallax',
            name='descripcion_corta_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripció curta'),
        ),
    ]
