# Generated by Django 4.2.2 on 2024-02-26 12:59

from django.db import migrations, models
import django.db.models.deletion
import multimedia_manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0020_parallax_descripcion_corta_ca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Títol del Carrusel')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('activo', models.BooleanField(default=True, verbose_name='Actiu')),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carrusels',
            },
        ),
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_carrusel/', validators=[multimedia_manager.utils.validar_tamanio_archivo], verbose_name='Imatge')),
                ('orden', models.PositiveIntegerField(default=0, help_text="Defineix l'ordre de la imatge en el carrusel", verbose_name='Ordre')),
                ('carrusel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imatges', to='multimedia_manager.carrusel', verbose_name='Carrusel')),
            ],
            options={
                'verbose_name': 'Imatge del Carrusel',
                'verbose_name_plural': 'Imatges del Carrusel',
                'ordering': ['orden'],
            },
        ),
    ]
