# Generated by Django 4.2.2 on 2024-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0023_alter_imagencarrusel_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagencarrusel',
            name='descripcion_ca',
            field=models.TextField(blank=True, help_text="Descripció per l'imatge que sortirà a la web.", null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='imagencarrusel',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text="Descripció per l'imatge que sortirà a la web.", null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='imagencarrusel',
            name='descripcion_es',
            field=models.TextField(blank=True, help_text="Descripció per l'imatge que sortirà a la web.", null=True, verbose_name='Caption'),
        ),
    ]
