# Generated by Django 4.2.2 on 2024-03-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0025_carrusel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallax',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Títol'),
        ),
    ]
