# Generated by Django 4.2.2 on 2024-04-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0026_alter_parallax_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagencarrusel',
            name='descripcion_fr',
            field=models.TextField(blank=True, help_text="Descripció per l'imatge que sortirà a la web.", null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='parallax',
            name='descripcion_corta_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripció curta'),
        ),
    ]
