# Generated by Django 4.2 on 2023-05-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0044_alter_categoria_publicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('post', 'Post'), ('categoria', 'Categoría'), ('subblog', 'SubBlog'), ('externo', 'Enlace Externo')], max_length=10)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria')),
                ('header', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='header.header')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('subblog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subblog')),
            ],
        ),
        migrations.CreateModel(
            name='EnlaceExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Títol de l'enllaç", max_length=15)),
                ('enlace', models.URLField(blank=True, help_text='Enllaç extern', null=True)),
                ('referencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='header.referencia')),
            ],
        ),
    ]
