# Generated by Django 4.2.1 on 2023-05-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='elementos_referencia',
        ),
        migrations.AddField(
            model_name='referencia',
            name='header',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='header.header'),
        ),
    ]
