# Generated by Django 4.2 on 2023-05-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlaceexterno',
            name='referencia',
        ),
        migrations.AddField(
            model_name='referencia',
            name='externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='header.enlaceexterno'),
        ),
    ]
