# Generated by Django 4.2.2 on 2023-06-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0003_alter_contacto_descripcion'),
        ('header', '0002_remove_enlaceexterno_referencia_referencia_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paginas_estaticas.contacto'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='tipo',
            field=models.CharField(choices=[('post', 'Post'), ('categoria', 'Categoría'), ('subblog', 'SubBlog'), ('externo', 'Enlace Externo'), ('contacto', 'Contacto')], max_length=10),
        ),
    ]
