# Generated by Django 4.2.2 on 2023-07-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_referencia_evento_especial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencia',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='referencia',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
