# Generated by Django 4.2.2 on 2023-08-10 10:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0007_remove_referencia_color_fondo_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_fondo_header', colorfield.fields.ColorField(default='#0000', image_field=None, max_length=18, samples=None)),
                ('color_letra', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='referencia',
            name='subvencion',
            field=models.BooleanField(blank=True, default=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='tipo',
            field=models.CharField(choices=[('post', 'Post'), ('categoria', 'Categoría'), ('subblog', 'SubBlog'), ('externo', 'Enlace Externo'), ('contacto', 'Contacto'), ('evento_especial', 'evento_especial'), ('subvencion', 'Sub')], max_length=30),
        ),
    ]
