# Generated by Django 4.2.2 on 2023-08-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0009_alter_referencia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='header_footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='header.headerfooter'),
        ),
    ]
