# Generated by Django 4.2.2 on 2023-08-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0011_alter_referencia_subvencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='subvencion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
