# Generated by Django 4.2.2 on 2023-08-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0003_subvenciondescripcion'),
        ('header', '0012_alter_referencia_subvencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='subvencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subvenciones.subvenciondescripcion'),
        ),
    ]
