# Generated by Django 4.2.2 on 2023-08-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0012_alter_referencia_subvencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='subvencion',
        ),
    ]
