# Generated by Django 4.2.2 on 2023-09-14 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0006_alter_cookies_metadescripcion_and_more'),
        ('header', '0015_referencia_subvencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='punt_informacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paginas_estaticas.puntoinformacion'),
        ),
    ]
