# Generated by Django 4.2.2 on 2023-09-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0010_alter_diversidadimagenbanner_diversidad'),
        ('compra_y_descubre', '0004_remove_compradescubre_parallax'),
        ('eventos_especiales', '0014_alter_eventoespecial_agendas'),
        ('blog', '0079_alter_categoria_tipo'),
        ('subvenciones', '0011_alter_subvencion_metadescripcion_and_more'),
        ('header', '0018_alter_referencia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='compra_y_descubre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra_y_descubre.compradescubre', verbose_name='compra i descobreix'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paginas_estaticas.contacto', verbose_name='contacte'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='evento_especial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos_especiales.eventoespecial', verbose_name='esdeveniment'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='header.enlaceexterno', verbose_name='extern'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='header',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='header.header', verbose_name='capcelera'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='header_footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='header.headerfooter', verbose_name='capcelera inferior'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='punt_informacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paginas_estaticas.puntoinformacion', verbose_name="punt d'informació"),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='subvencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subvenciones.subvenciondescripcion', verbose_name='subvenció'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='tipo',
            field=models.CharField(choices=[('post', 'entrada'), ('categoria', 'Categoría'), ('subblog', 'SubBlog'), ('externo', 'Enllaç Extern'), ('contacto', 'Contacte'), ('evento_especial', 'esdeveniment especial'), ('compra_y_descubre', 'Compra i Descobreix'), ('subvencion', 'Subvenció'), ('punt_informacio', "punt d'informació")], help_text='selecciona el tipus de referencia que vols', max_length=30, verbose_name='Tipus'),
        ),
    ]
