# Generated by Django 4.2.2 on 2023-10-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0019_referencia_compra_y_descubre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enlaceexterno',
            options={'verbose_name': 'Enllaç extern', 'verbose_name_plural': 'Enllaços externs'},
        ),
    ]
