# Generated by Django 4.2.2 on 2023-10-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0020_alter_enlaceexterno_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlaceexterno',
            name='enlace',
            field=models.URLField(blank=True, help_text='Enllaç extern', null=True, verbose_name='enllaç'),
        ),
        migrations.AlterField(
            model_name='enlaceexterno',
            name='titulo',
            field=models.CharField(help_text="Títol de l'enllaç", max_length=35, verbose_name='títol'),
        ),
    ]
