# Generated by Django 4.2.2 on 2023-10-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0021_alter_enlaceexterno_enlace_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencia',
            options={'ordering': ['orden'], 'verbose_name': 'Referències', 'verbose_name_plural': 'Referència'},
        ),
    ]
