# Generated by Django 4.2.2 on 2024-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0022_alter_referencia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlaceexterno',
            name='titulo_ca',
            field=models.CharField(help_text="Títol de l'enllaç", max_length=35, null=True, verbose_name='títol'),
        ),
        migrations.AddField(
            model_name='enlaceexterno',
            name='titulo_en',
            field=models.CharField(help_text="Títol de l'enllaç", max_length=35, null=True, verbose_name='títol'),
        ),
        migrations.AddField(
            model_name='enlaceexterno',
            name='titulo_es',
            field=models.CharField(help_text="Títol de l'enllaç", max_length=35, null=True, verbose_name='títol'),
        ),
    ]
