# Generated by Django 4.2.2 on 2024-02-28 08:01

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0024_header_color_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlaceexterno',
            name='color_letra',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='enlaceexterno',
            name='estil_del_text',
            field=models.CharField(blank=True, choices=[('text-decoration-none', 'Sense decoració de text'), ('fw-bold', 'Text en negreta'), ('text-primary', 'Text color primari'), ('text-secondary', 'Text color secundari'), ('text-uppercase', 'Text en majúscules'), ('text-lowercase', 'Text en minúscules'), ('text-capitalize', 'Text capitalitzat')], default='text-decoration-none', help_text="Selecciona un estil de Bootstrap per a l'estilització personalitzada", max_length=50, verbose_name='estil del text'),
        ),
    ]
