# Generated by Django 4.2.2 on 2024-02-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0025_enlaceexterno_color_letra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlaceexterno',
            name='estil_del_text',
            field=models.CharField(blank=True, choices=[('text-decoration-none', 'Sense decoració de text'), ('fw-bold', 'Text en negreta'), ('text-uppercase', 'Text en majúscules'), ('text-lowercase', 'Text en minúscules'), ('text-capitalize', 'Text capitalitzat')], default='text-decoration-none', help_text="Selecciona un estil de Bootstrap per a l'estilització personalitzada", max_length=50, verbose_name='estil del text'),
        ),
    ]
