# Generated by Django 4.2.2 on 2024-03-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0026_alter_enlaceexterno_estil_del_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='logo_auxiliar',
            field=models.ImageField(blank=True, help_text='Logo auxiliar per afegir el logo del turisme sostenible.', null=True, upload_to='logo_auxiliar/'),
        ),
    ]
