# Generated by Django 4.2.2 on 2024-03-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0028_header_logo_auxiliar_2_header_logo_auxiliar_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='logo_auxiliar/')),
                ('titulo', models.CharField(blank=True, help_text='Títol opcional per al logo.', max_length=100, null=True)),
                ('enlace', models.URLField(blank=True, help_text='Enllaç opcional per al logo.', null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos_auxiliares', to='header.header')),
            ],
        ),
    ]
