# Generated by Django 4.2.2 on 2024-03-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0030_logoauxiliar_titulo_ca_logoauxiliar_titulo_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='logo_auxiliar',
        ),
        migrations.RemoveField(
            model_name='header',
            name='logo_auxiliar_2',
        ),
        migrations.RemoveField(
            model_name='header',
            name='logo_auxiliar_3',
        ),
    ]
