# Generated by Django 4.2.2 on 2024-03-12 14:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0032_alter_logoauxiliar_options_logoauxiliar_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='color_top_bar_logos',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
