# Generated by Django 4.2.2 on 2024-04-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0033_header_color_top_bar_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlaceexterno',
            name='titulo_fr',
            field=models.CharField(help_text="Títol de l'enllaç", max_length=35, null=True, verbose_name='títol'),
        ),
        migrations.AddField(
            model_name='logoauxiliar',
            name='titulo_fr',
            field=models.CharField(blank=True, help_text='Títol opcional per al logo.', max_length=100, null=True),
        ),
    ]
