# Generated by Django 5.1.2 on 2025-10-08 19:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0035_logoauxiliar_mostrar_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlaceexterno',
            name='color_letra',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='header',
            name='color_entrada',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='header',
            name='color_fondo_header',
            field=colorfield.fields.ColorField(default='#0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='header',
            name='color_letra',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='header',
            name='color_top_bar_logos',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='color_fondo_header',
            field=colorfield.fields.ColorField(default='#0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='headerfooter',
            name='color_letra',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
