# Generated by Django 4.2.2 on 2023-08-10 09:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subvencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data de creació')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Data de modificació')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True)),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True)),
                ('titulo', models.CharField(help_text='Introdueix el títol de la subvenció.', max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField(help_text='Introdueix la descripció de la subvenció.')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si el subblog està publicat')),
                ('archivo', models.FileField(upload_to='subvenciones/')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subvenció',
                'verbose_name_plural': 'Subvencions',
            },
        ),
    ]
