# Generated by Django 4.2.2 on 2023-08-10 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
