# Generated by Django 4.2.2 on 2023-08-10 13:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0002_subvencion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubvencionDescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True)),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True)),
                ('titulo', models.CharField(help_text='Introdueix el títol.', max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField(help_text='Introdueix la descripció.')),
            ],
            options={
                'verbose_name': 'Descripció de llistat de les subvencions',
                'verbose_name_plural': 'Descripció de llistat de les subvencions',
            },
        ),
    ]
