# Generated by Django 4.2.2 on 2023-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0003_subvenciondescripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvenciondescripcion',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Selecciona una imatge per a la subvenció.', null=True, upload_to='subvencions'),
        ),
    ]
