# Generated by Django 4.2.2 on 2023-08-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0006_subvencion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvenciondescripcion',
            name='disclaimer',
            field=models.TextField(blank=True, help_text='Afegiu qualsevol informació addicional o notes importants aquí.'),
        ),
    ]
