# Generated by Django 4.2.2 on 2023-08-11 09:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0007_subvenciondescripcion_disclaimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvenciondescripcion',
            name='disclaimer',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Afegiu qualsevol informació addicional o notes importants aquí.'),
        ),
    ]
