# Generated by Django 4.2.2 on 2023-08-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0011_alter_video_archivo'),
        ('subvenciones', '0009_subvencion_disclaimer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subvencion',
            name='archivo',
        ),
        migrations.CreateModel(
            name='PDFCollectionTotesFichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Introdueix el títol.', max_length=100)),
                ('fichero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero')),
                ('subvencion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subvenciones.subvencion')),
            ],
        ),
        migrations.CreateModel(
            name='PDFCollectionResolucioFichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Introdueix el títol.', max_length=100)),
                ('fichero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero')),
                ('subvencion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subvenciones.subvencion')),
            ],
        ),
        migrations.CreateModel(
            name='PDFCollectionJustificacioFichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Introdueix el títol.', max_length=100)),
                ('fichero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero')),
                ('subvencion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subvenciones.subvencion')),
            ],
        ),
        migrations.CreateModel(
            name='PDFCollectionConvocatoriaFichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Introdueix el títol.', max_length=100)),
                ('fichero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero')),
                ('subvencion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subvenciones.subvencion')),
            ],
        ),
    ]
