# Generated by Django 5.1.2 on 2025-10-08 19:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0011_alter_subvencion_metadescripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvencion',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Introdueix la descripció de la subvenció.'),
        ),
        migrations.AlterField(
            model_name='subvencion',
            name='disclaimer',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Afegiu qualsevol informació addicional o notes importants aquí.'),
        ),
        migrations.AlterField(
            model_name='subvenciondescripcion',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Introdueix la descripció.'),
        ),
        migrations.AlterField(
            model_name='subvenciondescripcion',
            name='disclaimer',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Afegiu qualsevol informació addicional o notes importants aquí.'),
        ),
    ]
