# Generated by Django 4.2.1 on 2023-05-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal', '0002_alter_paginalegal_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(help_text='Agrega una imagen(143 x 72 px) relevante para el diseño del footer.', upload_to='footer_empresas/')),
                ('enlace', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Footer Empresa',
                'verbose_name_plural': 'Footer Empresas',
            },
        ),
        migrations.CreateModel(
            name='FooterInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Agrega una imagen relevante para la información del footer.', upload_to='footer/')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('paginas_legales', models.ManyToManyField(to='legal.paginalegal')),
            ],
        ),
    ]
