# Generated by Django 3.2.19 on 2023-06-07 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paginas_estaticas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Agrega una imagen relevante para la información del footer.', upload_to='footer/')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('footer', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='footer.footer')),
                ('paginas_legales', models.ManyToManyField(to='paginas_estaticas.PaginaLegal')),
            ],
        ),
        migrations.CreateModel(
            name='FooterEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(help_text='Agrega una imagen(143 x 72 px) relevante para el diseño del footer.', upload_to='footer_empresas/')),
                ('enlace', models.URLField(blank=True, null=True)),
                ('footer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='footer.footer')),
            ],
            options={
                'verbose_name': 'Footer Empresa',
                'verbose_name_plural': 'Footer Empresas',
            },
        ),
    ]
