# Generated by Django 4.2.1 on 2023-05-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerempresa',
            name='footer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='footer.footer'),
        ),
        migrations.AddField(
            model_name='footerinformacion',
            name='footer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='footer.footer'),
        ),
    ]
