# Generated by Django 4.2.2 on 2024-02-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0016_diversidad_descripcion_auxiliar_ca_and_more'),
        ('footer', '0002_alter_footerempresa_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerinformacion',
            options={'verbose_name': 'Informació del Footer', 'verbose_name_plural': 'Informacions del Footer'},
        ),
        migrations.AlterField(
            model_name='footerempresa',
            name='enlace',
            field=models.URLField(blank=True, help_text="Afegeix un enllaç opcional per a l'empresa.", null=True, verbose_name='Enllaç'),
        ),
        migrations.AlterField(
            model_name='footerempresa',
            name='footer',
            field=models.ForeignKey(help_text="Selecciona el footer al qual pertany l'empresa.", on_delete=django.db.models.deletion.CASCADE, to='footer.footer', verbose_name='Footer associat'),
        ),
        migrations.AlterField(
            model_name='footerempresa',
            name='imagen',
            field=models.ImageField(help_text='Afegeix una imatge (143 x 72 px) rellevant per al disseny del footer.', upload_to='footer_empresas/', verbose_name='Imatge'),
        ),
        migrations.AlterField(
            model_name='footerempresa',
            name='titulo',
            field=models.CharField(help_text="Afegeix un títol per a l'empresa en el footer.", max_length=100, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='footerinformacion',
            name='correo_contacto',
            field=models.EmailField(help_text="Afegeix l'adreça de correu electrònic de contacte.", max_length=254, verbose_name='Correu de contacte'),
        ),
        migrations.AlterField(
            model_name='footerinformacion',
            name='direccion',
            field=models.CharField(help_text='Especifica la direcció de contacte.', max_length=100, verbose_name='Direcció'),
        ),
        migrations.AlterField(
            model_name='footerinformacion',
            name='footer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='footer.footer'),
        ),
        migrations.AlterField(
            model_name='footerinformacion',
            name='imagen',
            field=models.ImageField(help_text='Afegeix una imatge rellevant per a la informació del footer.', upload_to='footer/', verbose_name='Imatge'),
        ),
        migrations.AlterField(
            model_name='footerinformacion',
            name='paginas_legales',
            field=models.ManyToManyField(help_text='Selecciona les pàgines legals vinculades a la informació del footer.', to='paginas_estaticas.paginalegal', verbose_name='Pàgines legals'),
        ),
        migrations.AlterField(
            model_name='footerinformacion',
            name='telefono',
            field=models.CharField(help_text='Afegeix el número de telèfon de contacte.', max_length=20, verbose_name='Telèfon'),
        ),
    ]
