# Generated by Django 3.2.19 on 2023-06-07 07:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaEstatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True)),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaginaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('privacitat', 'Política de privacitat'), ('avis_legal', 'Avís legal'), ('cookies', 'Política de cookies')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('encabezado', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='legal_images/')),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('paginaestatica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginas_estaticas.paginaestatica')),
                ('banner', models.ImageField(upload_to='agenda_banners')),
            ],
            options={
                'abstract': False,
            },
            bases=('paginas_estaticas.paginaestatica',),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('paginaestatica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginas_estaticas.paginaestatica')),
                ('banner', models.ImageField(blank=True, help_text='Banner del contacto', null=True, upload_to='contacto/')),
                ('subtitulo', models.CharField(blank=True, help_text='Subtítulo del contacto', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del contacto')),
            ],
            options={
                'abstract': False,
            },
            bases=('paginas_estaticas.paginaestatica',),
        ),
        migrations.CreateModel(
            name='PuntoInformacion',
            fields=[
                ('paginaestatica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginas_estaticas.paginaestatica')),
                ('telefono', models.CharField(help_text='Telèfon de contacte', max_length=20)),
                ('correo', models.EmailField(help_text='Correu electrònic de contacte', max_length=254)),
                ('direccion', models.CharField(help_text='Adreça', max_length=255)),
                ('banner', models.ImageField(help_text="Banner del punt d'informació", upload_to='punto_informacion_banners')),
                ('descripcion', ckeditor.fields.RichTextField(help_text="Descripció del punt d'informació")),
                ('latitud', models.FloatField(help_text='Latitud per a Google Maps')),
                ('longitud', models.FloatField(help_text='Longitud per a Google Maps')),
            ],
            options={
                'abstract': False,
            },
            bases=('paginas_estaticas.paginaestatica',),
        ),
    ]
