# Generated by Django 3.2.19 on 2023-06-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
