# Generated by Django 4.2.2 on 2023-07-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_mappoint_contenido_adicional'),
        ('paginas_estaticas', '0003_alter_contacto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntoinformacion',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='puntoinformacion',
            name='longitud',
        ),
        migrations.AddField(
            model_name='puntoinformacion',
            name='mapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.mappoint'),
        ),
    ]
