# Generated by Django 4.2.2 on 2023-08-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0004_remove_puntoinformacion_latitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True)),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True)),
                ('titulo', models.CharField(help_text='Título de la política de cookies', max_length=100)),
                ('contenido', models.TextField(help_text='Contenido de la política de cookies')),
            ],
            options={
                'verbose_name_plural': 'Políticas de Cookies',
            },
        ),
    ]
