# Generated by Django 4.2.2 on 2023-09-14 07:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_mappoint_enlace_google_maps_alter_mappoint_calle_and_more'),
        ('paginas_estaticas', '0006_alter_cookies_metadescripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginaestatica',
            name='titulo',
        ),
        migrations.AddField(
            model_name='contacto',
            name='titulo',
            field=models.CharField(default='Títol per defecte', max_length=255, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='puntoinformacion',
            name='titulo',
            field=models.CharField(default='Títol per defecte', max_length=255, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner del contacto', null=True, upload_to='contacto/', verbose_name='Banner del contacto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(help_text='Descripción del contacto', verbose_name='Descripció del contacte'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Subtítulo del contacto', max_length=100, verbose_name='Subtítol del contacto'),
        ),
        migrations.AlterField(
            model_name='cookies',
            name='contenido',
            field=models.TextField(help_text='Contenido de la política de cookies', verbose_name='Contingut de la política de cookies'),
        ),
        migrations.AlterField(
            model_name='cookies',
            name='titulo',
            field=models.CharField(help_text='Título de la política de cookies', max_length=100, verbose_name='Títol de la política de cookies'),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='banner',
            field=models.ImageField(help_text="Banner del punt d'informació", upload_to='punto_informacion_banners', verbose_name="Banner del punt d'informació"),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='correo',
            field=models.EmailField(help_text='Correu electrònic de contacte', max_length=254, verbose_name='Correu electrònic de contacte'),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(help_text="Descripció del punt d'informació", verbose_name="Descripció del punt d'informació"),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='direccion',
            field=models.CharField(help_text='Adreça', max_length=255, verbose_name='Adreça'),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='mapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.mappoint', verbose_name='Mapa'),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='telefono',
            field=models.CharField(help_text='Telèfon de contacte', max_length=20, verbose_name='Telèfon de contacte'),
        ),
    ]
