# Generated by Django 4.2.2 on 2023-09-20 10:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0013_fichero_titulo'),
        ('blog', '0079_alter_categoria_tipo'),
        ('paginas_estaticas', '0007_remove_paginaestatica_titulo_contacto_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diversidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitulo', models.CharField(blank=True, help_text='Metatítol per a SEO', max_length=255, null=True, verbose_name='Metatítol')),
                ('metadescripcion', models.TextField(blank=True, help_text='Metadescripció per a SEO', null=True, verbose_name='Metadescripció')),
                ('titulo', models.CharField(help_text='afegeix el titul principal', max_length=255)),
                ('sub_titulo', models.CharField(blank=True, help_text='afegeix un subtitul per la landing de igualtat', max_length=255, null=True)),
                ('descripcion_auxiliar', ckeditor.fields.RichTextField(blank=True, help_text='Explica a el pla de igualtat', null=True, verbose_name='descripció auxiliar')),
                ('logros', models.ManyToManyField(blank=True, help_text='Afegeix els èxits que hem obtingut PE (punt lila o els punts segurs)', related_name='logros_diversidad', to='blog.post', verbose_name='èxits')),
                ('planes', models.ManyToManyField(blank=True, help_text='Afegeix els plans que estem seguint per arribar a la igualtat.', related_name='planes_diversidad', to='blog.post', verbose_name='plans')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFDiversidadFichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Introdueix el títol.', max_length=100)),
                ('diversidad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paginas_estaticas.diversidad', verbose_name='diversitat')),
                ('fichero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero')),
            ],
        ),
        migrations.CreateModel(
            name='DiversidadImagenBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='afegeix el nom de la entitat', max_length=255, verbose_name='nom')),
                ('enlace', models.URLField(blank=True, help_text="Enllaç a cap el lloc virtual de l'entitat", null=True, verbose_name="Enllaç de l'entitat")),
                ('diversidad', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paginas_estaticas.diversidad', verbose_name='Entrada del Bloc')),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.imagen', verbose_name='Imatge')),
            ],
            options={
                'verbose_name': "Imatge de l'entitat",
                'verbose_name_plural': 'Imatges de les entitats',
            },
        ),
    ]
