# Generated by Django 4.2.2 on 2023-09-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0013_fichero_titulo'),
        ('paginas_estaticas', '0008_diversidad_pdfdiversidadfichero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diversidad',
            options={'verbose_name': 'diversitat', 'verbose_name_plural': 'diversitat'},
        ),
        migrations.AlterField(
            model_name='diversidad',
            name='sub_titulo',
            field=models.CharField(blank=True, help_text='afegeix un subtitul per la landing de igualtat', max_length=255, null=True, verbose_name='subtítul'),
        ),
        migrations.AlterField(
            model_name='diversidad',
            name='titulo',
            field=models.CharField(help_text='afegeix el titul principal', max_length=255, verbose_name='títul'),
        ),
        migrations.AlterField(
            model_name='pdfdiversidadfichero',
            name='fichero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia_manager.fichero', verbose_name='fitxer'),
        ),
        migrations.AlterField(
            model_name='pdfdiversidadfichero',
            name='titulo',
            field=models.CharField(help_text='Introdueix el títol.', max_length=100, verbose_name='títul'),
        ),
    ]
