# Generated by Django 4.2.2 on 2023-09-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0009_alter_diversidad_options_alter_diversidad_sub_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diversidadimagenbanner',
            name='diversidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paginas_estaticas.diversidad', verbose_name='Entrada del Bloc'),
        ),
    ]
