# Generated by Django 4.2.2 on 2024-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0010_alter_diversidadimagenbanner_diversidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginalegal',
            name='encabezado_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paginalegal',
            name='encabezado_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paginalegal',
            name='encabezado_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paginalegal',
            name='titulo_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paginalegal',
            name='titulo_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paginalegal',
            name='titulo_es',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
