# Generated by Django 4.2.2 on 2024-02-13 14:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0012_paginalegal_contenido_ca_paginalegal_contenido_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoinformacion',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(help_text="Descripció del punt d'informació", null=True, verbose_name="Descripció del punt d'informació"),
        ),
        migrations.AddField(
            model_name='puntoinformacion',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(help_text="Descripció del punt d'informació", null=True, verbose_name="Descripció del punt d'informació"),
        ),
        migrations.AddField(
            model_name='puntoinformacion',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(help_text="Descripció del punt d'informació", null=True, verbose_name="Descripció del punt d'informació"),
        ),
        migrations.AddField(
            model_name='puntoinformacion',
            name='titulo_ca',
            field=models.CharField(default='Títol per defecte', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='puntoinformacion',
            name='titulo_en',
            field=models.CharField(default='Títol per defecte', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='puntoinformacion',
            name='titulo_es',
            field=models.CharField(default='Títol per defecte', max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
