# Generated by Django 4.2.2 on 2024-02-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0013_puntoinformacion_descripcion_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookies',
            name='contenido_ca',
            field=models.TextField(help_text='Contenido de la política de cookies', null=True, verbose_name='Contingut de la política de cookies'),
        ),
        migrations.AddField(
            model_name='cookies',
            name='contenido_en',
            field=models.TextField(help_text='Contenido de la política de cookies', null=True, verbose_name='Contingut de la política de cookies'),
        ),
        migrations.AddField(
            model_name='cookies',
            name='contenido_es',
            field=models.TextField(help_text='Contenido de la política de cookies', null=True, verbose_name='Contingut de la política de cookies'),
        ),
        migrations.AddField(
            model_name='cookies',
            name='titulo_ca',
            field=models.CharField(help_text='Título de la política de cookies', max_length=100, null=True, verbose_name='Títol de la política de cookies'),
        ),
        migrations.AddField(
            model_name='cookies',
            name='titulo_en',
            field=models.CharField(help_text='Título de la política de cookies', max_length=100, null=True, verbose_name='Títol de la política de cookies'),
        ),
        migrations.AddField(
            model_name='cookies',
            name='titulo_es',
            field=models.CharField(help_text='Título de la política de cookies', max_length=100, null=True, verbose_name='Títol de la política de cookies'),
        ),
    ]
