# Generated by Django 4.2.2 on 2024-02-14 10:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0014_cookies_contenido_ca_cookies_contenido_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='descripcion_ca',
            field=ckeditor.fields.RichTextField(help_text='Descripción del contacto', null=True, verbose_name='Descripció del contacte'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(help_text='Descripción del contacto', null=True, verbose_name='Descripció del contacte'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(help_text='Descripción del contacto', null=True, verbose_name='Descripció del contacte'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='subtitulo_ca',
            field=models.CharField(blank=True, help_text='Subtítulo del contacto', max_length=100, null=True, verbose_name='Subtítol del contacto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='subtitulo_en',
            field=models.CharField(blank=True, help_text='Subtítulo del contacto', max_length=100, null=True, verbose_name='Subtítol del contacto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='subtitulo_es',
            field=models.CharField(blank=True, help_text='Subtítulo del contacto', max_length=100, null=True, verbose_name='Subtítol del contacto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='titulo_ca',
            field=models.CharField(default='Títol per defecte', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='titulo_en',
            field=models.CharField(default='Títol per defecte', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='titulo_es',
            field=models.CharField(default='Títol per defecte', max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
