# Generated by Django 4.2.2 on 2024-02-14 10:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0015_contacto_descripcion_ca_contacto_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diversidad',
            name='descripcion_auxiliar_ca',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explica a el pla de igualtat', null=True, verbose_name='descripció auxiliar'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='descripcion_auxiliar_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explica a el pla de igualtat', null=True, verbose_name='descripció auxiliar'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='descripcion_auxiliar_es',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explica a el pla de igualtat', null=True, verbose_name='descripció auxiliar'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='sub_titulo_ca',
            field=models.CharField(blank=True, help_text='afegeix un subtitul per la landing de igualtat', max_length=255, null=True, verbose_name='subtítul'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='sub_titulo_en',
            field=models.CharField(blank=True, help_text='afegeix un subtitul per la landing de igualtat', max_length=255, null=True, verbose_name='subtítul'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='sub_titulo_es',
            field=models.CharField(blank=True, help_text='afegeix un subtitul per la landing de igualtat', max_length=255, null=True, verbose_name='subtítul'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='titulo_ca',
            field=models.CharField(help_text='afegeix el titul principal', max_length=255, null=True, verbose_name='títul'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='titulo_en',
            field=models.CharField(help_text='afegeix el titul principal', max_length=255, null=True, verbose_name='títul'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='titulo_es',
            field=models.CharField(help_text='afegeix el titul principal', max_length=255, null=True, verbose_name='títul'),
        ),
    ]
