# Generated by Django 4.2.2 on 2024-04-06 20:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0016_diversidad_descripcion_auxiliar_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='descripcion_fr',
            field=ckeditor.fields.RichTextField(help_text='Descripción del contacto', null=True, verbose_name='Descripció del contacte'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='subtitulo_fr',
            field=models.CharField(blank=True, help_text='Subtítulo del contacto', max_length=100, null=True, verbose_name='Subtítol del contacto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='titulo_fr',
            field=models.CharField(default='Títol per defecte', max_length=255, null=True, verbose_name='Títol'),
        ),
        migrations.AddField(
            model_name='cookies',
            name='contenido_fr',
            field=models.TextField(help_text='Contenido de la política de cookies', null=True, verbose_name='Contingut de la política de cookies'),
        ),
        migrations.AddField(
            model_name='cookies',
            name='titulo_fr',
            field=models.CharField(help_text='Título de la política de cookies', max_length=100, null=True, verbose_name='Títol de la política de cookies'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='descripcion_auxiliar_fr',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explica a el pla de igualtat', null=True, verbose_name='descripció auxiliar'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='sub_titulo_fr',
            field=models.CharField(blank=True, help_text='afegeix un subtitul per la landing de igualtat', max_length=255, null=True, verbose_name='subtítul'),
        ),
        migrations.AddField(
            model_name='diversidad',
            name='titulo_fr',
            field=models.CharField(help_text='afegeix el titul principal', max_length=255, null=True, verbose_name='títul'),
        ),
        migrations.AddField(
            model_name='paginalegal',
            name='contenido_fr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='paginalegal',
            name='encabezado_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paginalegal',
            name='titulo_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puntoinformacion',
            name='descripcion_fr',
            field=ckeditor.fields.RichTextField(help_text="Descripció del punt d'informació", null=True, verbose_name="Descripció del punt d'informació"),
        ),
        migrations.AddField(
            model_name='puntoinformacion',
            name='titulo_fr',
            field=models.CharField(default='Títol per defecte', max_length=255, null=True, verbose_name='Títol'),
        ),
    ]
