# Generated by Django 5.1.2 on 2025-10-08 19:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_estaticas', '0017_contacto_descripcion_fr_contacto_subtitulo_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripción del contacto', verbose_name='Descripció del contacte'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='descripcion_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripción del contacto', null=True, verbose_name='Descripció del contacte'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='descripcion_en',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripción del contacto', null=True, verbose_name='Descripció del contacte'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='descripcion_es',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripción del contacto', null=True, verbose_name='Descripció del contacte'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='descripcion_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Descripción del contacto', null=True, verbose_name='Descripció del contacte'),
        ),
        migrations.AlterField(
            model_name='diversidad',
            name='descripcion_auxiliar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explica a el pla de igualtat', null=True, verbose_name='descripció auxiliar'),
        ),
        migrations.AlterField(
            model_name='diversidad',
            name='descripcion_auxiliar_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explica a el pla de igualtat', null=True, verbose_name='descripció auxiliar'),
        ),
        migrations.AlterField(
            model_name='diversidad',
            name='descripcion_auxiliar_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explica a el pla de igualtat', null=True, verbose_name='descripció auxiliar'),
        ),
        migrations.AlterField(
            model_name='diversidad',
            name='descripcion_auxiliar_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explica a el pla de igualtat', null=True, verbose_name='descripció auxiliar'),
        ),
        migrations.AlterField(
            model_name='diversidad',
            name='descripcion_auxiliar_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explica a el pla de igualtat', null=True, verbose_name='descripció auxiliar'),
        ),
        migrations.AlterField(
            model_name='paginalegal',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='paginalegal',
            name='contenido_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
        migrations.AlterField(
            model_name='paginalegal',
            name='contenido_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
        migrations.AlterField(
            model_name='paginalegal',
            name='contenido_es',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
        migrations.AlterField(
            model_name='paginalegal',
            name='contenido_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Descripció del punt d'informació", verbose_name="Descripció del punt d'informació"),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='descripcion_ca',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Descripció del punt d'informació", null=True, verbose_name="Descripció del punt d'informació"),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='descripcion_en',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Descripció del punt d'informació", null=True, verbose_name="Descripció del punt d'informació"),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='descripcion_es',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Descripció del punt d'informació", null=True, verbose_name="Descripció del punt d'informació"),
        ),
        migrations.AlterField(
            model_name='puntoinformacion',
            name='descripcion_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Descripció del punt d'informació", null=True, verbose_name="Descripció del punt d'informació"),
        ),
    ]
